/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PublicInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicInterface{}

// PublicInterface struct for PublicInterface
type PublicInterface struct {
	Interface string `json:"interface"`
	Ipv4 string `json:"ipv4"`
	Ipv6 string `json:"ipv6"`
	// ID or slug
	FwRulesSet NullableString `json:"fw_rules_set,omitempty"`
	FwPolicyIn *FwPolicyOutEnum `json:"fw_policy_in,omitempty"`
	FwPolicyOut *FwPolicyOutEnum `json:"fw_policy_out,omitempty"`
}

type _PublicInterface PublicInterface

// NewPublicInterface instantiates a new PublicInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicInterface(interface_ string, ipv4 string, ipv6 string) *PublicInterface {
	this := PublicInterface{}
	this.Interface = interface_
	this.Ipv4 = ipv4
	this.Ipv6 = ipv6
	return &this
}

// NewPublicInterfaceWithDefaults instantiates a new PublicInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicInterfaceWithDefaults() *PublicInterface {
	this := PublicInterface{}
	return &this
}

// GetInterface returns the Interface field value
func (o *PublicInterface) GetInterface() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Interface
}

// GetInterfaceOk returns a tuple with the Interface field value
// and a boolean to check if the value has been set.
func (o *PublicInterface) GetInterfaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Interface, true
}

// SetInterface sets field value
func (o *PublicInterface) SetInterface(v string) {
	o.Interface = v
}

// GetIpv4 returns the Ipv4 field value
func (o *PublicInterface) GetIpv4() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ipv4
}

// GetIpv4Ok returns a tuple with the Ipv4 field value
// and a boolean to check if the value has been set.
func (o *PublicInterface) GetIpv4Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ipv4, true
}

// SetIpv4 sets field value
func (o *PublicInterface) SetIpv4(v string) {
	o.Ipv4 = v
}

// GetIpv6 returns the Ipv6 field value
func (o *PublicInterface) GetIpv6() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ipv6
}

// GetIpv6Ok returns a tuple with the Ipv6 field value
// and a boolean to check if the value has been set.
func (o *PublicInterface) GetIpv6Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ipv6, true
}

// SetIpv6 sets field value
func (o *PublicInterface) SetIpv6(v string) {
	o.Ipv6 = v
}

// GetFwRulesSet returns the FwRulesSet field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicInterface) GetFwRulesSet() string {
	if o == nil || IsNil(o.FwRulesSet.Get()) {
		var ret string
		return ret
	}
	return *o.FwRulesSet.Get()
}

// GetFwRulesSetOk returns a tuple with the FwRulesSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicInterface) GetFwRulesSetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FwRulesSet.Get(), o.FwRulesSet.IsSet()
}

// HasFwRulesSet returns a boolean if a field has been set.
func (o *PublicInterface) HasFwRulesSet() bool {
	if o != nil && o.FwRulesSet.IsSet() {
		return true
	}

	return false
}

// SetFwRulesSet gets a reference to the given NullableString and assigns it to the FwRulesSet field.
func (o *PublicInterface) SetFwRulesSet(v string) {
	o.FwRulesSet.Set(&v)
}
// SetFwRulesSetNil sets the value for FwRulesSet to be an explicit nil
func (o *PublicInterface) SetFwRulesSetNil() {
	o.FwRulesSet.Set(nil)
}

// UnsetFwRulesSet ensures that no value is present for FwRulesSet, not even an explicit nil
func (o *PublicInterface) UnsetFwRulesSet() {
	o.FwRulesSet.Unset()
}

// GetFwPolicyIn returns the FwPolicyIn field value if set, zero value otherwise.
func (o *PublicInterface) GetFwPolicyIn() FwPolicyOutEnum {
	if o == nil || IsNil(o.FwPolicyIn) {
		var ret FwPolicyOutEnum
		return ret
	}
	return *o.FwPolicyIn
}

// GetFwPolicyInOk returns a tuple with the FwPolicyIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicInterface) GetFwPolicyInOk() (*FwPolicyOutEnum, bool) {
	if o == nil || IsNil(o.FwPolicyIn) {
		return nil, false
	}
	return o.FwPolicyIn, true
}

// HasFwPolicyIn returns a boolean if a field has been set.
func (o *PublicInterface) HasFwPolicyIn() bool {
	if o != nil && !IsNil(o.FwPolicyIn) {
		return true
	}

	return false
}

// SetFwPolicyIn gets a reference to the given FwPolicyOutEnum and assigns it to the FwPolicyIn field.
func (o *PublicInterface) SetFwPolicyIn(v FwPolicyOutEnum) {
	o.FwPolicyIn = &v
}

// GetFwPolicyOut returns the FwPolicyOut field value if set, zero value otherwise.
func (o *PublicInterface) GetFwPolicyOut() FwPolicyOutEnum {
	if o == nil || IsNil(o.FwPolicyOut) {
		var ret FwPolicyOutEnum
		return ret
	}
	return *o.FwPolicyOut
}

// GetFwPolicyOutOk returns a tuple with the FwPolicyOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicInterface) GetFwPolicyOutOk() (*FwPolicyOutEnum, bool) {
	if o == nil || IsNil(o.FwPolicyOut) {
		return nil, false
	}
	return o.FwPolicyOut, true
}

// HasFwPolicyOut returns a boolean if a field has been set.
func (o *PublicInterface) HasFwPolicyOut() bool {
	if o != nil && !IsNil(o.FwPolicyOut) {
		return true
	}

	return false
}

// SetFwPolicyOut gets a reference to the given FwPolicyOutEnum and assigns it to the FwPolicyOut field.
func (o *PublicInterface) SetFwPolicyOut(v FwPolicyOutEnum) {
	o.FwPolicyOut = &v
}

func (o PublicInterface) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["interface"] = o.Interface
	toSerialize["ipv4"] = o.Ipv4
	toSerialize["ipv6"] = o.Ipv6
	if o.FwRulesSet.IsSet() {
		toSerialize["fw_rules_set"] = o.FwRulesSet.Get()
	}
	if !IsNil(o.FwPolicyIn) {
		toSerialize["fw_policy_in"] = o.FwPolicyIn
	}
	if !IsNil(o.FwPolicyOut) {
		toSerialize["fw_policy_out"] = o.FwPolicyOut
	}
	return toSerialize, nil
}

func (o *PublicInterface) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"interface",
		"ipv4",
		"ipv6",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublicInterface := _PublicInterface{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPublicInterface)

	if err != nil {
		return err
	}

	*o = PublicInterface(varPublicInterface)

	return err
}

type NullablePublicInterface struct {
	value *PublicInterface
	isSet bool
}

func (v NullablePublicInterface) Get() *PublicInterface {
	return v.value
}

func (v *NullablePublicInterface) Set(val *PublicInterface) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicInterface) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicInterface(val *PublicInterface) *NullablePublicInterface {
	return &NullablePublicInterface{value: val, isSet: true}
}

func (v NullablePublicInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


