/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"fmt"
)

// Status03cEnum * `unpaid` - Unpaid * `paid` - Paid * `paid_with_funds` - Paid with funds * `overdue` - Overdue * `processing` - Processing * `cancelled` - Cancelled * `refunded` - Refunded
type Status03cEnum string

// List of Status03cEnum
const (
	STATUS03CENUM_UNPAID Status03cEnum = "unpaid"
	STATUS03CENUM_PAID Status03cEnum = "paid"
	STATUS03CENUM_PAID_WITH_FUNDS Status03cEnum = "paid_with_funds"
	STATUS03CENUM_OVERDUE Status03cEnum = "overdue"
	STATUS03CENUM_PROCESSING Status03cEnum = "processing"
	STATUS03CENUM_CANCELLED Status03cEnum = "cancelled"
	STATUS03CENUM_REFUNDED Status03cEnum = "refunded"
)

// All allowed values of Status03cEnum enum
var AllowedStatus03cEnumEnumValues = []Status03cEnum{
	"unpaid",
	"paid",
	"paid_with_funds",
	"overdue",
	"processing",
	"cancelled",
	"refunded",
}

func (v *Status03cEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Status03cEnum(value)
	for _, existing := range AllowedStatus03cEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Status03cEnum", value)
}

// NewStatus03cEnumFromValue returns a pointer to a valid Status03cEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewStatus03cEnumFromValue(v string) (*Status03cEnum, error) {
	ev := Status03cEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Status03cEnum: valid values are %v", v, AllowedStatus03cEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Status03cEnum) IsValid() bool {
	for _, existing := range AllowedStatus03cEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Status03cEnum value
func (v Status03cEnum) Ptr() *Status03cEnum {
	return &v
}

type NullableStatus03cEnum struct {
	value *Status03cEnum
	isSet bool
}

func (v NullableStatus03cEnum) Get() *Status03cEnum {
	return v.value
}

func (v *NullableStatus03cEnum) Set(val *Status03cEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableStatus03cEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableStatus03cEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatus03cEnum(val *Status03cEnum) *NullableStatus03cEnum {
	return &NullableStatus03cEnum{value: val, isSet: true}
}

func (v NullableStatus03cEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatus03cEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

