/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClusterDetailRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterDetailRequest{}

// ClusterDetailRequest struct for ClusterDetailRequest
type ClusterDetailRequest struct {
	Name *string `json:"name,omitempty"`
	PricePerMonth string `json:"price_per_month" validate:"regexp=^-?\\d{0\\,16}(?:\\.\\d{0\\,4})?$"`
	Features []FeaturesEnum `json:"features,omitempty"`
	Protected *bool `json:"protected,omitempty"`
}

type _ClusterDetailRequest ClusterDetailRequest

// NewClusterDetailRequest instantiates a new ClusterDetailRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterDetailRequest(pricePerMonth string) *ClusterDetailRequest {
	this := ClusterDetailRequest{}
	this.PricePerMonth = pricePerMonth
	return &this
}

// NewClusterDetailRequestWithDefaults instantiates a new ClusterDetailRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterDetailRequestWithDefaults() *ClusterDetailRequest {
	this := ClusterDetailRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ClusterDetailRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDetailRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ClusterDetailRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ClusterDetailRequest) SetName(v string) {
	o.Name = &v
}

// GetPricePerMonth returns the PricePerMonth field value
func (o *ClusterDetailRequest) GetPricePerMonth() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PricePerMonth
}

// GetPricePerMonthOk returns a tuple with the PricePerMonth field value
// and a boolean to check if the value has been set.
func (o *ClusterDetailRequest) GetPricePerMonthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PricePerMonth, true
}

// SetPricePerMonth sets field value
func (o *ClusterDetailRequest) SetPricePerMonth(v string) {
	o.PricePerMonth = v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *ClusterDetailRequest) GetFeatures() []FeaturesEnum {
	if o == nil || IsNil(o.Features) {
		var ret []FeaturesEnum
		return ret
	}
	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDetailRequest) GetFeaturesOk() ([]FeaturesEnum, bool) {
	if o == nil || IsNil(o.Features) {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *ClusterDetailRequest) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given []FeaturesEnum and assigns it to the Features field.
func (o *ClusterDetailRequest) SetFeatures(v []FeaturesEnum) {
	o.Features = v
}

// GetProtected returns the Protected field value if set, zero value otherwise.
func (o *ClusterDetailRequest) GetProtected() bool {
	if o == nil || IsNil(o.Protected) {
		var ret bool
		return ret
	}
	return *o.Protected
}

// GetProtectedOk returns a tuple with the Protected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDetailRequest) GetProtectedOk() (*bool, bool) {
	if o == nil || IsNil(o.Protected) {
		return nil, false
	}
	return o.Protected, true
}

// HasProtected returns a boolean if a field has been set.
func (o *ClusterDetailRequest) HasProtected() bool {
	if o != nil && !IsNil(o.Protected) {
		return true
	}

	return false
}

// SetProtected gets a reference to the given bool and assigns it to the Protected field.
func (o *ClusterDetailRequest) SetProtected(v bool) {
	o.Protected = &v
}

func (o ClusterDetailRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterDetailRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["price_per_month"] = o.PricePerMonth
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}
	if !IsNil(o.Protected) {
		toSerialize["protected"] = o.Protected
	}
	return toSerialize, nil
}

func (o *ClusterDetailRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"price_per_month",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterDetailRequest := _ClusterDetailRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varClusterDetailRequest)

	if err != nil {
		return err
	}

	*o = ClusterDetailRequest(varClusterDetailRequest)

	return err
}

type NullableClusterDetailRequest struct {
	value *ClusterDetailRequest
	isSet bool
}

func (v NullableClusterDetailRequest) Get() *ClusterDetailRequest {
	return v.value
}

func (v *NullableClusterDetailRequest) Set(val *ClusterDetailRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterDetailRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterDetailRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterDetailRequest(val *ClusterDetailRequest) *NullableClusterDetailRequest {
	return &NullableClusterDetailRequest{value: val, isSet: true}
}

func (v NullableClusterDetailRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterDetailRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


