/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ActivateFreeDNSResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActivateFreeDNSResponse{}

// ActivateFreeDNSResponse struct for ActivateFreeDNSResponse
type ActivateFreeDNSResponse struct {
	Message string `json:"message"`
	Domain string `json:"domain"`
	Source string `json:"source"`
}

type _ActivateFreeDNSResponse ActivateFreeDNSResponse

// NewActivateFreeDNSResponse instantiates a new ActivateFreeDNSResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActivateFreeDNSResponse(message string, domain string, source string) *ActivateFreeDNSResponse {
	this := ActivateFreeDNSResponse{}
	this.Message = message
	this.Domain = domain
	this.Source = source
	return &this
}

// NewActivateFreeDNSResponseWithDefaults instantiates a new ActivateFreeDNSResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActivateFreeDNSResponseWithDefaults() *ActivateFreeDNSResponse {
	this := ActivateFreeDNSResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *ActivateFreeDNSResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ActivateFreeDNSResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ActivateFreeDNSResponse) SetMessage(v string) {
	o.Message = v
}

// GetDomain returns the Domain field value
func (o *ActivateFreeDNSResponse) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *ActivateFreeDNSResponse) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *ActivateFreeDNSResponse) SetDomain(v string) {
	o.Domain = v
}

// GetSource returns the Source field value
func (o *ActivateFreeDNSResponse) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *ActivateFreeDNSResponse) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *ActivateFreeDNSResponse) SetSource(v string) {
	o.Source = v
}

func (o ActivateFreeDNSResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActivateFreeDNSResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["domain"] = o.Domain
	toSerialize["source"] = o.Source
	return toSerialize, nil
}

func (o *ActivateFreeDNSResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"domain",
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActivateFreeDNSResponse := _ActivateFreeDNSResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varActivateFreeDNSResponse)

	if err != nil {
		return err
	}

	*o = ActivateFreeDNSResponse(varActivateFreeDNSResponse)

	return err
}

type NullableActivateFreeDNSResponse struct {
	value *ActivateFreeDNSResponse
	isSet bool
}

func (v NullableActivateFreeDNSResponse) Get() *ActivateFreeDNSResponse {
	return v.value
}

func (v *NullableActivateFreeDNSResponse) Set(val *ActivateFreeDNSResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableActivateFreeDNSResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableActivateFreeDNSResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActivateFreeDNSResponse(val *ActivateFreeDNSResponse) *NullableActivateFreeDNSResponse {
	return &NullableActivateFreeDNSResponse{value: val, isSet: true}
}

func (v NullableActivateFreeDNSResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActivateFreeDNSResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


