/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaginatedClusterDetailList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedClusterDetailList{}

// PaginatedClusterDetailList struct for PaginatedClusterDetailList
type PaginatedClusterDetailList struct {
	Count int32 `json:"count"`
	Next NullableString `json:"next,omitempty"`
	Previous NullableString `json:"previous,omitempty"`
	Results []ClusterDetail `json:"results"`
}

type _PaginatedClusterDetailList PaginatedClusterDetailList

// NewPaginatedClusterDetailList instantiates a new PaginatedClusterDetailList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedClusterDetailList(count int32, results []ClusterDetail) *PaginatedClusterDetailList {
	this := PaginatedClusterDetailList{}
	this.Count = count
	this.Results = results
	return &this
}

// NewPaginatedClusterDetailListWithDefaults instantiates a new PaginatedClusterDetailList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedClusterDetailListWithDefaults() *PaginatedClusterDetailList {
	this := PaginatedClusterDetailList{}
	return &this
}

// GetCount returns the Count field value
func (o *PaginatedClusterDetailList) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *PaginatedClusterDetailList) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *PaginatedClusterDetailList) SetCount(v int32) {
	o.Count = v
}

// GetNext returns the Next field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedClusterDetailList) GetNext() string {
	if o == nil || IsNil(o.Next.Get()) {
		var ret string
		return ret
	}
	return *o.Next.Get()
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedClusterDetailList) GetNextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Next.Get(), o.Next.IsSet()
}

// HasNext returns a boolean if a field has been set.
func (o *PaginatedClusterDetailList) HasNext() bool {
	if o != nil && o.Next.IsSet() {
		return true
	}

	return false
}

// SetNext gets a reference to the given NullableString and assigns it to the Next field.
func (o *PaginatedClusterDetailList) SetNext(v string) {
	o.Next.Set(&v)
}
// SetNextNil sets the value for Next to be an explicit nil
func (o *PaginatedClusterDetailList) SetNextNil() {
	o.Next.Set(nil)
}

// UnsetNext ensures that no value is present for Next, not even an explicit nil
func (o *PaginatedClusterDetailList) UnsetNext() {
	o.Next.Unset()
}

// GetPrevious returns the Previous field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedClusterDetailList) GetPrevious() string {
	if o == nil || IsNil(o.Previous.Get()) {
		var ret string
		return ret
	}
	return *o.Previous.Get()
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedClusterDetailList) GetPreviousOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Previous.Get(), o.Previous.IsSet()
}

// HasPrevious returns a boolean if a field has been set.
func (o *PaginatedClusterDetailList) HasPrevious() bool {
	if o != nil && o.Previous.IsSet() {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given NullableString and assigns it to the Previous field.
func (o *PaginatedClusterDetailList) SetPrevious(v string) {
	o.Previous.Set(&v)
}
// SetPreviousNil sets the value for Previous to be an explicit nil
func (o *PaginatedClusterDetailList) SetPreviousNil() {
	o.Previous.Set(nil)
}

// UnsetPrevious ensures that no value is present for Previous, not even an explicit nil
func (o *PaginatedClusterDetailList) UnsetPrevious() {
	o.Previous.Unset()
}

// GetResults returns the Results field value
func (o *PaginatedClusterDetailList) GetResults() []ClusterDetail {
	if o == nil {
		var ret []ClusterDetail
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedClusterDetailList) GetResultsOk() ([]ClusterDetail, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedClusterDetailList) SetResults(v []ClusterDetail) {
	o.Results = v
}

func (o PaginatedClusterDetailList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedClusterDetailList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	if o.Next.IsSet() {
		toSerialize["next"] = o.Next.Get()
	}
	if o.Previous.IsSet() {
		toSerialize["previous"] = o.Previous.Get()
	}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *PaginatedClusterDetailList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedClusterDetailList := _PaginatedClusterDetailList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedClusterDetailList)

	if err != nil {
		return err
	}

	*o = PaginatedClusterDetailList(varPaginatedClusterDetailList)

	return err
}

type NullablePaginatedClusterDetailList struct {
	value *PaginatedClusterDetailList
	isSet bool
}

func (v NullablePaginatedClusterDetailList) Get() *PaginatedClusterDetailList {
	return v.value
}

func (v *NullablePaginatedClusterDetailList) Set(val *PaginatedClusterDetailList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedClusterDetailList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedClusterDetailList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedClusterDetailList(val *PaginatedClusterDetailList) *NullablePaginatedClusterDetailList {
	return &NullablePaginatedClusterDetailList{value: val, isSet: true}
}

func (v NullablePaginatedClusterDetailList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedClusterDetailList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


