/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"fmt"
)

// EncryptionModeEnum * `none` - none * `wireguard` - wireguard
type EncryptionModeEnum string

// List of EncryptionModeEnum
const (
	ENCRYPTIONMODEENUM_NONE EncryptionModeEnum = "none"
	ENCRYPTIONMODEENUM_WIREGUARD EncryptionModeEnum = "wireguard"
)

// All allowed values of EncryptionModeEnum enum
var AllowedEncryptionModeEnumEnumValues = []EncryptionModeEnum{
	"none",
	"wireguard",
}

func (v *EncryptionModeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EncryptionModeEnum(value)
	for _, existing := range AllowedEncryptionModeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EncryptionModeEnum", value)
}

// NewEncryptionModeEnumFromValue returns a pointer to a valid EncryptionModeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEncryptionModeEnumFromValue(v string) (*EncryptionModeEnum, error) {
	ev := EncryptionModeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EncryptionModeEnum: valid values are %v", v, AllowedEncryptionModeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EncryptionModeEnum) IsValid() bool {
	for _, existing := range AllowedEncryptionModeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EncryptionModeEnum value
func (v EncryptionModeEnum) Ptr() *EncryptionModeEnum {
	return &v
}

type NullableEncryptionModeEnum struct {
	value *EncryptionModeEnum
	isSet bool
}

func (v NullableEncryptionModeEnum) Get() *EncryptionModeEnum {
	return v.value
}

func (v *NullableEncryptionModeEnum) Set(val *EncryptionModeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableEncryptionModeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableEncryptionModeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEncryptionModeEnum(val *EncryptionModeEnum) *NullableEncryptionModeEnum {
	return &NullableEncryptionModeEnum{value: val, isSet: true}
}

func (v NullableEncryptionModeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEncryptionModeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

