/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"fmt"
)

// ScopeEnum * `read_only` - Read only * `read_write` - Read & Write
type ScopeEnum string

// List of ScopeEnum
const (
	SCOPEENUM_READ_ONLY ScopeEnum = "read_only"
	SCOPEENUM_READ_WRITE ScopeEnum = "read_write"
)

// All allowed values of ScopeEnum enum
var AllowedScopeEnumEnumValues = []ScopeEnum{
	"read_only",
	"read_write",
}

func (v *ScopeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ScopeEnum(value)
	for _, existing := range AllowedScopeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ScopeEnum", value)
}

// NewScopeEnumFromValue returns a pointer to a valid ScopeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewScopeEnumFromValue(v string) (*ScopeEnum, error) {
	ev := ScopeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ScopeEnum: valid values are %v", v, AllowedScopeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ScopeEnum) IsValid() bool {
	for _, existing := range AllowedScopeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ScopeEnum value
func (v ScopeEnum) Ptr() *ScopeEnum {
	return &v
}

type NullableScopeEnum struct {
	value *ScopeEnum
	isSet bool
}

func (v NullableScopeEnum) Get() *ScopeEnum {
	return v.value
}

func (v *NullableScopeEnum) Set(val *ScopeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableScopeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableScopeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScopeEnum(val *ScopeEnum) *NullableScopeEnum {
	return &NullableScopeEnum{value: val, isSet: true}
}

func (v NullableScopeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScopeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

