/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
)

// checks if the PatchedUDPRouteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedUDPRouteRequest{}

// PatchedUDPRouteRequest Serializer for UDPRoute resources with port validation.
type PatchedUDPRouteRequest struct {
	Name *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	// External port to expose
	Port *int32 `json:"port,omitempty"`
	// Name of the backend Kubernetes Service
	BackendServiceName *string `json:"backend_service_name,omitempty"`
	// Port of the backend Service
	BackendServicePort *int32 `json:"backend_service_port,omitempty"`
	// Namespace of the backend Service
	BackendNamespace *string `json:"backend_namespace,omitempty"`
}

// NewPatchedUDPRouteRequest instantiates a new PatchedUDPRouteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedUDPRouteRequest() *PatchedUDPRouteRequest {
	this := PatchedUDPRouteRequest{}
	var backendNamespace string = "default"
	this.BackendNamespace = &backendNamespace
	return &this
}

// NewPatchedUDPRouteRequestWithDefaults instantiates a new PatchedUDPRouteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedUDPRouteRequestWithDefaults() *PatchedUDPRouteRequest {
	this := PatchedUDPRouteRequest{}
	var backendNamespace string = "default"
	this.BackendNamespace = &backendNamespace
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedUDPRouteRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedUDPRouteRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedUDPRouteRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedUDPRouteRequest) SetName(v string) {
	o.Name = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *PatchedUDPRouteRequest) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedUDPRouteRequest) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *PatchedUDPRouteRequest) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *PatchedUDPRouteRequest) SetNamespace(v string) {
	o.Namespace = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *PatchedUDPRouteRequest) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedUDPRouteRequest) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *PatchedUDPRouteRequest) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *PatchedUDPRouteRequest) SetPort(v int32) {
	o.Port = &v
}

// GetBackendServiceName returns the BackendServiceName field value if set, zero value otherwise.
func (o *PatchedUDPRouteRequest) GetBackendServiceName() string {
	if o == nil || IsNil(o.BackendServiceName) {
		var ret string
		return ret
	}
	return *o.BackendServiceName
}

// GetBackendServiceNameOk returns a tuple with the BackendServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedUDPRouteRequest) GetBackendServiceNameOk() (*string, bool) {
	if o == nil || IsNil(o.BackendServiceName) {
		return nil, false
	}
	return o.BackendServiceName, true
}

// HasBackendServiceName returns a boolean if a field has been set.
func (o *PatchedUDPRouteRequest) HasBackendServiceName() bool {
	if o != nil && !IsNil(o.BackendServiceName) {
		return true
	}

	return false
}

// SetBackendServiceName gets a reference to the given string and assigns it to the BackendServiceName field.
func (o *PatchedUDPRouteRequest) SetBackendServiceName(v string) {
	o.BackendServiceName = &v
}

// GetBackendServicePort returns the BackendServicePort field value if set, zero value otherwise.
func (o *PatchedUDPRouteRequest) GetBackendServicePort() int32 {
	if o == nil || IsNil(o.BackendServicePort) {
		var ret int32
		return ret
	}
	return *o.BackendServicePort
}

// GetBackendServicePortOk returns a tuple with the BackendServicePort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedUDPRouteRequest) GetBackendServicePortOk() (*int32, bool) {
	if o == nil || IsNil(o.BackendServicePort) {
		return nil, false
	}
	return o.BackendServicePort, true
}

// HasBackendServicePort returns a boolean if a field has been set.
func (o *PatchedUDPRouteRequest) HasBackendServicePort() bool {
	if o != nil && !IsNil(o.BackendServicePort) {
		return true
	}

	return false
}

// SetBackendServicePort gets a reference to the given int32 and assigns it to the BackendServicePort field.
func (o *PatchedUDPRouteRequest) SetBackendServicePort(v int32) {
	o.BackendServicePort = &v
}

// GetBackendNamespace returns the BackendNamespace field value if set, zero value otherwise.
func (o *PatchedUDPRouteRequest) GetBackendNamespace() string {
	if o == nil || IsNil(o.BackendNamespace) {
		var ret string
		return ret
	}
	return *o.BackendNamespace
}

// GetBackendNamespaceOk returns a tuple with the BackendNamespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedUDPRouteRequest) GetBackendNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.BackendNamespace) {
		return nil, false
	}
	return o.BackendNamespace, true
}

// HasBackendNamespace returns a boolean if a field has been set.
func (o *PatchedUDPRouteRequest) HasBackendNamespace() bool {
	if o != nil && !IsNil(o.BackendNamespace) {
		return true
	}

	return false
}

// SetBackendNamespace gets a reference to the given string and assigns it to the BackendNamespace field.
func (o *PatchedUDPRouteRequest) SetBackendNamespace(v string) {
	o.BackendNamespace = &v
}

func (o PatchedUDPRouteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedUDPRouteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.BackendServiceName) {
		toSerialize["backend_service_name"] = o.BackendServiceName
	}
	if !IsNil(o.BackendServicePort) {
		toSerialize["backend_service_port"] = o.BackendServicePort
	}
	if !IsNil(o.BackendNamespace) {
		toSerialize["backend_namespace"] = o.BackendNamespace
	}
	return toSerialize, nil
}

type NullablePatchedUDPRouteRequest struct {
	value *PatchedUDPRouteRequest
	isSet bool
}

func (v NullablePatchedUDPRouteRequest) Get() *PatchedUDPRouteRequest {
	return v.value
}

func (v *NullablePatchedUDPRouteRequest) Set(val *PatchedUDPRouteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedUDPRouteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedUDPRouteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedUDPRouteRequest(val *PatchedUDPRouteRequest) *NullablePatchedUDPRouteRequest {
	return &NullablePatchedUDPRouteRequest{value: val, isSet: true}
}

func (v NullablePatchedUDPRouteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedUDPRouteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


