/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ActivateFreeDNS type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActivateFreeDNS{}

// ActivateFreeDNS struct for ActivateFreeDNS
type ActivateFreeDNS struct {
	// Domain name or primary key of the domain to activate.
	Domain string `json:"domain"`
	// 'internal' for domains purchased on PidginHost, 'external' for user-added domains.  * `internal` - Internal * `external` - External
	Source SourceEnum `json:"source"`
	// IPv4 address to use as the default A record for the zone.
	Ip string `json:"ip"`
}

type _ActivateFreeDNS ActivateFreeDNS

// NewActivateFreeDNS instantiates a new ActivateFreeDNS object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActivateFreeDNS(domain string, source SourceEnum, ip string) *ActivateFreeDNS {
	this := ActivateFreeDNS{}
	this.Domain = domain
	this.Source = source
	this.Ip = ip
	return &this
}

// NewActivateFreeDNSWithDefaults instantiates a new ActivateFreeDNS object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActivateFreeDNSWithDefaults() *ActivateFreeDNS {
	this := ActivateFreeDNS{}
	return &this
}

// GetDomain returns the Domain field value
func (o *ActivateFreeDNS) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *ActivateFreeDNS) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *ActivateFreeDNS) SetDomain(v string) {
	o.Domain = v
}

// GetSource returns the Source field value
func (o *ActivateFreeDNS) GetSource() SourceEnum {
	if o == nil {
		var ret SourceEnum
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *ActivateFreeDNS) GetSourceOk() (*SourceEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *ActivateFreeDNS) SetSource(v SourceEnum) {
	o.Source = v
}

// GetIp returns the Ip field value
func (o *ActivateFreeDNS) GetIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ip
}

// GetIpOk returns a tuple with the Ip field value
// and a boolean to check if the value has been set.
func (o *ActivateFreeDNS) GetIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ip, true
}

// SetIp sets field value
func (o *ActivateFreeDNS) SetIp(v string) {
	o.Ip = v
}

func (o ActivateFreeDNS) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActivateFreeDNS) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domain"] = o.Domain
	toSerialize["source"] = o.Source
	toSerialize["ip"] = o.Ip
	return toSerialize, nil
}

func (o *ActivateFreeDNS) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domain",
		"source",
		"ip",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActivateFreeDNS := _ActivateFreeDNS{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varActivateFreeDNS)

	if err != nil {
		return err
	}

	*o = ActivateFreeDNS(varActivateFreeDNS)

	return err
}

type NullableActivateFreeDNS struct {
	value *ActivateFreeDNS
	isSet bool
}

func (v NullableActivateFreeDNS) Get() *ActivateFreeDNS {
	return v.value
}

func (v *NullableActivateFreeDNS) Set(val *ActivateFreeDNS) {
	v.value = val
	v.isSet = true
}

func (v NullableActivateFreeDNS) IsSet() bool {
	return v.isSet
}

func (v *NullableActivateFreeDNS) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActivateFreeDNS(val *ActivateFreeDNS) *NullableActivateFreeDNS {
	return &NullableActivateFreeDNS{value: val, isSet: true}
}

func (v NullableActivateFreeDNS) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActivateFreeDNS) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


