/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HTTPRouteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HTTPRouteRequest{}

// HTTPRouteRequest Serializer for HTTPRoute resources with automatic certificate issuance.
type HTTPRouteRequest struct {
	Name string `json:"name"`
	Namespace *string `json:"namespace,omitempty"`
	// List of hostnames to route (e.g., [\"example.com\", \"www.example.com\"])
	Hostnames []string `json:"hostnames"`
	// Name of the backend Kubernetes Service
	BackendServiceName string `json:"backend_service_name"`
	// Port of the backend Service
	BackendServicePort int32 `json:"backend_service_port"`
	// Namespace of the backend Service
	BackendNamespace *string `json:"backend_namespace,omitempty"`
	// Path prefix to match (default: /)
	PathPrefix *string `json:"path_prefix,omitempty"`
	// Enable TLS termination with automatic certificate issuance
	EnableTls *bool `json:"enable_tls,omitempty"`
}

type _HTTPRouteRequest HTTPRouteRequest

// NewHTTPRouteRequest instantiates a new HTTPRouteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHTTPRouteRequest(name string, hostnames []string, backendServiceName string, backendServicePort int32) *HTTPRouteRequest {
	this := HTTPRouteRequest{}
	this.Name = name
	this.Hostnames = hostnames
	this.BackendServiceName = backendServiceName
	this.BackendServicePort = backendServicePort
	var backendNamespace string = "default"
	this.BackendNamespace = &backendNamespace
	var pathPrefix string = "/"
	this.PathPrefix = &pathPrefix
	var enableTls bool = true
	this.EnableTls = &enableTls
	return &this
}

// NewHTTPRouteRequestWithDefaults instantiates a new HTTPRouteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHTTPRouteRequestWithDefaults() *HTTPRouteRequest {
	this := HTTPRouteRequest{}
	var backendNamespace string = "default"
	this.BackendNamespace = &backendNamespace
	var pathPrefix string = "/"
	this.PathPrefix = &pathPrefix
	var enableTls bool = true
	this.EnableTls = &enableTls
	return &this
}

// GetName returns the Name field value
func (o *HTTPRouteRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HTTPRouteRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HTTPRouteRequest) SetName(v string) {
	o.Name = v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *HTTPRouteRequest) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HTTPRouteRequest) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *HTTPRouteRequest) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *HTTPRouteRequest) SetNamespace(v string) {
	o.Namespace = &v
}

// GetHostnames returns the Hostnames field value
func (o *HTTPRouteRequest) GetHostnames() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Hostnames
}

// GetHostnamesOk returns a tuple with the Hostnames field value
// and a boolean to check if the value has been set.
func (o *HTTPRouteRequest) GetHostnamesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hostnames, true
}

// SetHostnames sets field value
func (o *HTTPRouteRequest) SetHostnames(v []string) {
	o.Hostnames = v
}

// GetBackendServiceName returns the BackendServiceName field value
func (o *HTTPRouteRequest) GetBackendServiceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BackendServiceName
}

// GetBackendServiceNameOk returns a tuple with the BackendServiceName field value
// and a boolean to check if the value has been set.
func (o *HTTPRouteRequest) GetBackendServiceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BackendServiceName, true
}

// SetBackendServiceName sets field value
func (o *HTTPRouteRequest) SetBackendServiceName(v string) {
	o.BackendServiceName = v
}

// GetBackendServicePort returns the BackendServicePort field value
func (o *HTTPRouteRequest) GetBackendServicePort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BackendServicePort
}

// GetBackendServicePortOk returns a tuple with the BackendServicePort field value
// and a boolean to check if the value has been set.
func (o *HTTPRouteRequest) GetBackendServicePortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BackendServicePort, true
}

// SetBackendServicePort sets field value
func (o *HTTPRouteRequest) SetBackendServicePort(v int32) {
	o.BackendServicePort = v
}

// GetBackendNamespace returns the BackendNamespace field value if set, zero value otherwise.
func (o *HTTPRouteRequest) GetBackendNamespace() string {
	if o == nil || IsNil(o.BackendNamespace) {
		var ret string
		return ret
	}
	return *o.BackendNamespace
}

// GetBackendNamespaceOk returns a tuple with the BackendNamespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HTTPRouteRequest) GetBackendNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.BackendNamespace) {
		return nil, false
	}
	return o.BackendNamespace, true
}

// HasBackendNamespace returns a boolean if a field has been set.
func (o *HTTPRouteRequest) HasBackendNamespace() bool {
	if o != nil && !IsNil(o.BackendNamespace) {
		return true
	}

	return false
}

// SetBackendNamespace gets a reference to the given string and assigns it to the BackendNamespace field.
func (o *HTTPRouteRequest) SetBackendNamespace(v string) {
	o.BackendNamespace = &v
}

// GetPathPrefix returns the PathPrefix field value if set, zero value otherwise.
func (o *HTTPRouteRequest) GetPathPrefix() string {
	if o == nil || IsNil(o.PathPrefix) {
		var ret string
		return ret
	}
	return *o.PathPrefix
}

// GetPathPrefixOk returns a tuple with the PathPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HTTPRouteRequest) GetPathPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.PathPrefix) {
		return nil, false
	}
	return o.PathPrefix, true
}

// HasPathPrefix returns a boolean if a field has been set.
func (o *HTTPRouteRequest) HasPathPrefix() bool {
	if o != nil && !IsNil(o.PathPrefix) {
		return true
	}

	return false
}

// SetPathPrefix gets a reference to the given string and assigns it to the PathPrefix field.
func (o *HTTPRouteRequest) SetPathPrefix(v string) {
	o.PathPrefix = &v
}

// GetEnableTls returns the EnableTls field value if set, zero value otherwise.
func (o *HTTPRouteRequest) GetEnableTls() bool {
	if o == nil || IsNil(o.EnableTls) {
		var ret bool
		return ret
	}
	return *o.EnableTls
}

// GetEnableTlsOk returns a tuple with the EnableTls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HTTPRouteRequest) GetEnableTlsOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableTls) {
		return nil, false
	}
	return o.EnableTls, true
}

// HasEnableTls returns a boolean if a field has been set.
func (o *HTTPRouteRequest) HasEnableTls() bool {
	if o != nil && !IsNil(o.EnableTls) {
		return true
	}

	return false
}

// SetEnableTls gets a reference to the given bool and assigns it to the EnableTls field.
func (o *HTTPRouteRequest) SetEnableTls(v bool) {
	o.EnableTls = &v
}

func (o HTTPRouteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HTTPRouteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	toSerialize["hostnames"] = o.Hostnames
	toSerialize["backend_service_name"] = o.BackendServiceName
	toSerialize["backend_service_port"] = o.BackendServicePort
	if !IsNil(o.BackendNamespace) {
		toSerialize["backend_namespace"] = o.BackendNamespace
	}
	if !IsNil(o.PathPrefix) {
		toSerialize["path_prefix"] = o.PathPrefix
	}
	if !IsNil(o.EnableTls) {
		toSerialize["enable_tls"] = o.EnableTls
	}
	return toSerialize, nil
}

func (o *HTTPRouteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"hostnames",
		"backend_service_name",
		"backend_service_port",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHTTPRouteRequest := _HTTPRouteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varHTTPRouteRequest)

	if err != nil {
		return err
	}

	*o = HTTPRouteRequest(varHTTPRouteRequest)

	return err
}

type NullableHTTPRouteRequest struct {
	value *HTTPRouteRequest
	isSet bool
}

func (v NullableHTTPRouteRequest) Get() *HTTPRouteRequest {
	return v.value
}

func (v *NullableHTTPRouteRequest) Set(val *HTTPRouteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableHTTPRouteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableHTTPRouteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHTTPRouteRequest(val *HTTPRouteRequest) *NullableHTTPRouteRequest {
	return &NullableHTTPRouteRequest{value: val, isSet: true}
}

func (v NullableHTTPRouteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHTTPRouteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


