/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PayWithFundsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayWithFundsResponse{}

// PayWithFundsResponse struct for PayWithFundsResponse
type PayWithFundsResponse struct {
	Message string `json:"message"`
	Balance float64 `json:"balance" validate:"regexp=^-?\\\\d{0,16}(?:\\\\.\\\\d{0,4})?$"`
}

type _PayWithFundsResponse PayWithFundsResponse

// NewPayWithFundsResponse instantiates a new PayWithFundsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPayWithFundsResponse(message string, balance float64) *PayWithFundsResponse {
	this := PayWithFundsResponse{}
	this.Message = message
	this.Balance = balance
	return &this
}

// NewPayWithFundsResponseWithDefaults instantiates a new PayWithFundsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayWithFundsResponseWithDefaults() *PayWithFundsResponse {
	this := PayWithFundsResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *PayWithFundsResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *PayWithFundsResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *PayWithFundsResponse) SetMessage(v string) {
	o.Message = v
}

// GetBalance returns the Balance field value
func (o *PayWithFundsResponse) GetBalance() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value
// and a boolean to check if the value has been set.
func (o *PayWithFundsResponse) GetBalanceOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Balance, true
}

// SetBalance sets field value
func (o *PayWithFundsResponse) SetBalance(v float64) {
	o.Balance = v
}

func (o PayWithFundsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayWithFundsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["balance"] = o.Balance
	return toSerialize, nil
}

func (o *PayWithFundsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"balance",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPayWithFundsResponse := _PayWithFundsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPayWithFundsResponse)

	if err != nil {
		return err
	}

	*o = PayWithFundsResponse(varPayWithFundsResponse)

	return err
}

type NullablePayWithFundsResponse struct {
	value *PayWithFundsResponse
	isSet bool
}

func (v NullablePayWithFundsResponse) Get() *PayWithFundsResponse {
	return v.value
}

func (v *NullablePayWithFundsResponse) Set(val *PayWithFundsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePayWithFundsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePayWithFundsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayWithFundsResponse(val *PayWithFundsResponse) *NullablePayWithFundsResponse {
	return &NullablePayWithFundsResponse{value: val, isSet: true}
}

func (v NullablePayWithFundsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayWithFundsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


