/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PrivateNetworkRemoveHost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateNetworkRemoveHost{}

// PrivateNetworkRemoveHost struct for PrivateNetworkRemoveHost
type PrivateNetworkRemoveHost struct {
	// Server hostname or private IP
	Server string `json:"server"`
}

type _PrivateNetworkRemoveHost PrivateNetworkRemoveHost

// NewPrivateNetworkRemoveHost instantiates a new PrivateNetworkRemoveHost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateNetworkRemoveHost(server string) *PrivateNetworkRemoveHost {
	this := PrivateNetworkRemoveHost{}
	this.Server = server
	return &this
}

// NewPrivateNetworkRemoveHostWithDefaults instantiates a new PrivateNetworkRemoveHost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateNetworkRemoveHostWithDefaults() *PrivateNetworkRemoveHost {
	this := PrivateNetworkRemoveHost{}
	return &this
}

// GetServer returns the Server field value
func (o *PrivateNetworkRemoveHost) GetServer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Server
}

// GetServerOk returns a tuple with the Server field value
// and a boolean to check if the value has been set.
func (o *PrivateNetworkRemoveHost) GetServerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Server, true
}

// SetServer sets field value
func (o *PrivateNetworkRemoveHost) SetServer(v string) {
	o.Server = v
}

func (o PrivateNetworkRemoveHost) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateNetworkRemoveHost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["server"] = o.Server
	return toSerialize, nil
}

func (o *PrivateNetworkRemoveHost) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"server",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrivateNetworkRemoveHost := _PrivateNetworkRemoveHost{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPrivateNetworkRemoveHost)

	if err != nil {
		return err
	}

	*o = PrivateNetworkRemoveHost(varPrivateNetworkRemoveHost)

	return err
}

type NullablePrivateNetworkRemoveHost struct {
	value *PrivateNetworkRemoveHost
	isSet bool
}

func (v NullablePrivateNetworkRemoveHost) Get() *PrivateNetworkRemoveHost {
	return v.value
}

func (v *NullablePrivateNetworkRemoveHost) Set(val *PrivateNetworkRemoveHost) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateNetworkRemoveHost) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateNetworkRemoveHost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateNetworkRemoveHost(val *PrivateNetworkRemoveHost) *NullablePrivateNetworkRemoveHost {
	return &NullablePrivateNetworkRemoveHost{value: val, isSet: true}
}

func (v NullablePrivateNetworkRemoveHost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateNetworkRemoveHost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


