/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
)

// checks if the PatchedCompanyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedCompanyRequest{}

// PatchedCompanyRequest struct for PatchedCompanyRequest
type PatchedCompanyRequest struct {
	Name *string `json:"name,omitempty"`
	CifVat *string `json:"cif_vat,omitempty"`
	Reg *string `json:"reg,omitempty"`
	Iban *string `json:"iban,omitempty"`
	Bank *string `json:"bank,omitempty"`
	ContactName *string `json:"contact_name,omitempty"`
	ContactEmail *string `json:"contact_email,omitempty"`
	Address *AddressRequest `json:"address,omitempty"`
}

// NewPatchedCompanyRequest instantiates a new PatchedCompanyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedCompanyRequest() *PatchedCompanyRequest {
	this := PatchedCompanyRequest{}
	return &this
}

// NewPatchedCompanyRequestWithDefaults instantiates a new PatchedCompanyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedCompanyRequestWithDefaults() *PatchedCompanyRequest {
	this := PatchedCompanyRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedCompanyRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedCompanyRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedCompanyRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedCompanyRequest) SetName(v string) {
	o.Name = &v
}

// GetCifVat returns the CifVat field value if set, zero value otherwise.
func (o *PatchedCompanyRequest) GetCifVat() string {
	if o == nil || IsNil(o.CifVat) {
		var ret string
		return ret
	}
	return *o.CifVat
}

// GetCifVatOk returns a tuple with the CifVat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedCompanyRequest) GetCifVatOk() (*string, bool) {
	if o == nil || IsNil(o.CifVat) {
		return nil, false
	}
	return o.CifVat, true
}

// HasCifVat returns a boolean if a field has been set.
func (o *PatchedCompanyRequest) HasCifVat() bool {
	if o != nil && !IsNil(o.CifVat) {
		return true
	}

	return false
}

// SetCifVat gets a reference to the given string and assigns it to the CifVat field.
func (o *PatchedCompanyRequest) SetCifVat(v string) {
	o.CifVat = &v
}

// GetReg returns the Reg field value if set, zero value otherwise.
func (o *PatchedCompanyRequest) GetReg() string {
	if o == nil || IsNil(o.Reg) {
		var ret string
		return ret
	}
	return *o.Reg
}

// GetRegOk returns a tuple with the Reg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedCompanyRequest) GetRegOk() (*string, bool) {
	if o == nil || IsNil(o.Reg) {
		return nil, false
	}
	return o.Reg, true
}

// HasReg returns a boolean if a field has been set.
func (o *PatchedCompanyRequest) HasReg() bool {
	if o != nil && !IsNil(o.Reg) {
		return true
	}

	return false
}

// SetReg gets a reference to the given string and assigns it to the Reg field.
func (o *PatchedCompanyRequest) SetReg(v string) {
	o.Reg = &v
}

// GetIban returns the Iban field value if set, zero value otherwise.
func (o *PatchedCompanyRequest) GetIban() string {
	if o == nil || IsNil(o.Iban) {
		var ret string
		return ret
	}
	return *o.Iban
}

// GetIbanOk returns a tuple with the Iban field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedCompanyRequest) GetIbanOk() (*string, bool) {
	if o == nil || IsNil(o.Iban) {
		return nil, false
	}
	return o.Iban, true
}

// HasIban returns a boolean if a field has been set.
func (o *PatchedCompanyRequest) HasIban() bool {
	if o != nil && !IsNil(o.Iban) {
		return true
	}

	return false
}

// SetIban gets a reference to the given string and assigns it to the Iban field.
func (o *PatchedCompanyRequest) SetIban(v string) {
	o.Iban = &v
}

// GetBank returns the Bank field value if set, zero value otherwise.
func (o *PatchedCompanyRequest) GetBank() string {
	if o == nil || IsNil(o.Bank) {
		var ret string
		return ret
	}
	return *o.Bank
}

// GetBankOk returns a tuple with the Bank field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedCompanyRequest) GetBankOk() (*string, bool) {
	if o == nil || IsNil(o.Bank) {
		return nil, false
	}
	return o.Bank, true
}

// HasBank returns a boolean if a field has been set.
func (o *PatchedCompanyRequest) HasBank() bool {
	if o != nil && !IsNil(o.Bank) {
		return true
	}

	return false
}

// SetBank gets a reference to the given string and assigns it to the Bank field.
func (o *PatchedCompanyRequest) SetBank(v string) {
	o.Bank = &v
}

// GetContactName returns the ContactName field value if set, zero value otherwise.
func (o *PatchedCompanyRequest) GetContactName() string {
	if o == nil || IsNil(o.ContactName) {
		var ret string
		return ret
	}
	return *o.ContactName
}

// GetContactNameOk returns a tuple with the ContactName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedCompanyRequest) GetContactNameOk() (*string, bool) {
	if o == nil || IsNil(o.ContactName) {
		return nil, false
	}
	return o.ContactName, true
}

// HasContactName returns a boolean if a field has been set.
func (o *PatchedCompanyRequest) HasContactName() bool {
	if o != nil && !IsNil(o.ContactName) {
		return true
	}

	return false
}

// SetContactName gets a reference to the given string and assigns it to the ContactName field.
func (o *PatchedCompanyRequest) SetContactName(v string) {
	o.ContactName = &v
}

// GetContactEmail returns the ContactEmail field value if set, zero value otherwise.
func (o *PatchedCompanyRequest) GetContactEmail() string {
	if o == nil || IsNil(o.ContactEmail) {
		var ret string
		return ret
	}
	return *o.ContactEmail
}

// GetContactEmailOk returns a tuple with the ContactEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedCompanyRequest) GetContactEmailOk() (*string, bool) {
	if o == nil || IsNil(o.ContactEmail) {
		return nil, false
	}
	return o.ContactEmail, true
}

// HasContactEmail returns a boolean if a field has been set.
func (o *PatchedCompanyRequest) HasContactEmail() bool {
	if o != nil && !IsNil(o.ContactEmail) {
		return true
	}

	return false
}

// SetContactEmail gets a reference to the given string and assigns it to the ContactEmail field.
func (o *PatchedCompanyRequest) SetContactEmail(v string) {
	o.ContactEmail = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *PatchedCompanyRequest) GetAddress() AddressRequest {
	if o == nil || IsNil(o.Address) {
		var ret AddressRequest
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedCompanyRequest) GetAddressOk() (*AddressRequest, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *PatchedCompanyRequest) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given AddressRequest and assigns it to the Address field.
func (o *PatchedCompanyRequest) SetAddress(v AddressRequest) {
	o.Address = &v
}

func (o PatchedCompanyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedCompanyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.CifVat) {
		toSerialize["cif_vat"] = o.CifVat
	}
	if !IsNil(o.Reg) {
		toSerialize["reg"] = o.Reg
	}
	if !IsNil(o.Iban) {
		toSerialize["iban"] = o.Iban
	}
	if !IsNil(o.Bank) {
		toSerialize["bank"] = o.Bank
	}
	if !IsNil(o.ContactName) {
		toSerialize["contact_name"] = o.ContactName
	}
	if !IsNil(o.ContactEmail) {
		toSerialize["contact_email"] = o.ContactEmail
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	return toSerialize, nil
}

type NullablePatchedCompanyRequest struct {
	value *PatchedCompanyRequest
	isSet bool
}

func (v NullablePatchedCompanyRequest) Get() *PatchedCompanyRequest {
	return v.value
}

func (v *NullablePatchedCompanyRequest) Set(val *PatchedCompanyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedCompanyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedCompanyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedCompanyRequest(val *PatchedCompanyRequest) *NullablePatchedCompanyRequest {
	return &NullablePatchedCompanyRequest{value: val, isSet: true}
}

func (v NullablePatchedCompanyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedCompanyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


