/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProfileRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileRequest{}

// ProfileRequest struct for ProfileRequest
type ProfileRequest struct {
	FirstName string `json:"first_name"`
	LastName string `json:"last_name"`
	Phone string `json:"phone"`
}

type _ProfileRequest ProfileRequest

// NewProfileRequest instantiates a new ProfileRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileRequest(firstName string, lastName string, phone string) *ProfileRequest {
	this := ProfileRequest{}
	this.FirstName = firstName
	this.LastName = lastName
	this.Phone = phone
	return &this
}

// NewProfileRequestWithDefaults instantiates a new ProfileRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileRequestWithDefaults() *ProfileRequest {
	this := ProfileRequest{}
	return &this
}

// GetFirstName returns the FirstName field value
func (o *ProfileRequest) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *ProfileRequest) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *ProfileRequest) SetFirstName(v string) {
	o.FirstName = v
}

// GetLastName returns the LastName field value
func (o *ProfileRequest) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *ProfileRequest) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *ProfileRequest) SetLastName(v string) {
	o.LastName = v
}

// GetPhone returns the Phone field value
func (o *ProfileRequest) GetPhone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
func (o *ProfileRequest) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phone, true
}

// SetPhone sets field value
func (o *ProfileRequest) SetPhone(v string) {
	o.Phone = v
}

func (o ProfileRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["first_name"] = o.FirstName
	toSerialize["last_name"] = o.LastName
	toSerialize["phone"] = o.Phone
	return toSerialize, nil
}

func (o *ProfileRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"first_name",
		"last_name",
		"phone",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProfileRequest := _ProfileRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varProfileRequest)

	if err != nil {
		return err
	}

	*o = ProfileRequest(varProfileRequest)

	return err
}

type NullableProfileRequest struct {
	value *ProfileRequest
	isSet bool
}

func (v NullableProfileRequest) Get() *ProfileRequest {
	return v.value
}

func (v *NullableProfileRequest) Set(val *ProfileRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileRequest(val *ProfileRequest) *NullableProfileRequest {
	return &NullableProfileRequest{value: val, isSet: true}
}

func (v NullableProfileRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


