/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"fmt"
)

// ReasonEnum * `hard_bounce` - Hard bounce * `complaint` - Complaint * `manual` - Manual * `unsubscribe` - Unsubscribe
type ReasonEnum string

// List of ReasonEnum
const (
	REASONENUM_HARD_BOUNCE ReasonEnum = "hard_bounce"
	REASONENUM_COMPLAINT ReasonEnum = "complaint"
	REASONENUM_MANUAL ReasonEnum = "manual"
	REASONENUM_UNSUBSCRIBE ReasonEnum = "unsubscribe"
)

// All allowed values of ReasonEnum enum
var AllowedReasonEnumEnumValues = []ReasonEnum{
	"hard_bounce",
	"complaint",
	"manual",
	"unsubscribe",
}

func (v *ReasonEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ReasonEnum(value)
	for _, existing := range AllowedReasonEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ReasonEnum", value)
}

// NewReasonEnumFromValue returns a pointer to a valid ReasonEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewReasonEnumFromValue(v string) (*ReasonEnum, error) {
	ev := ReasonEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ReasonEnum: valid values are %v", v, AllowedReasonEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ReasonEnum) IsValid() bool {
	for _, existing := range AllowedReasonEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ReasonEnum value
func (v ReasonEnum) Ptr() *ReasonEnum {
	return &v
}

type NullableReasonEnum struct {
	value *ReasonEnum
	isSet bool
}

func (v NullableReasonEnum) Get() *ReasonEnum {
	return v.value
}

func (v *NullableReasonEnum) Set(val *ReasonEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableReasonEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableReasonEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReasonEnum(val *ReasonEnum) *NullableReasonEnum {
	return &NullableReasonEnum{value: val, isSet: true}
}

func (v NullableReasonEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReasonEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

