/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BucketVisibilityRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BucketVisibilityRequest{}

// BucketVisibilityRequest struct for BucketVisibilityRequest
type BucketVisibilityRequest struct {
	PublicRead bool `json:"public_read"`
}

type _BucketVisibilityRequest BucketVisibilityRequest

// NewBucketVisibilityRequest instantiates a new BucketVisibilityRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBucketVisibilityRequest(publicRead bool) *BucketVisibilityRequest {
	this := BucketVisibilityRequest{}
	this.PublicRead = publicRead
	return &this
}

// NewBucketVisibilityRequestWithDefaults instantiates a new BucketVisibilityRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBucketVisibilityRequestWithDefaults() *BucketVisibilityRequest {
	this := BucketVisibilityRequest{}
	return &this
}

// GetPublicRead returns the PublicRead field value
func (o *BucketVisibilityRequest) GetPublicRead() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PublicRead
}

// GetPublicReadOk returns a tuple with the PublicRead field value
// and a boolean to check if the value has been set.
func (o *BucketVisibilityRequest) GetPublicReadOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicRead, true
}

// SetPublicRead sets field value
func (o *BucketVisibilityRequest) SetPublicRead(v bool) {
	o.PublicRead = v
}

func (o BucketVisibilityRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BucketVisibilityRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["public_read"] = o.PublicRead
	return toSerialize, nil
}

func (o *BucketVisibilityRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"public_read",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBucketVisibilityRequest := _BucketVisibilityRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varBucketVisibilityRequest)

	if err != nil {
		return err
	}

	*o = BucketVisibilityRequest(varBucketVisibilityRequest)

	return err
}

type NullableBucketVisibilityRequest struct {
	value *BucketVisibilityRequest
	isSet bool
}

func (v NullableBucketVisibilityRequest) Get() *BucketVisibilityRequest {
	return v.value
}

func (v *NullableBucketVisibilityRequest) Set(val *BucketVisibilityRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBucketVisibilityRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBucketVisibilityRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBucketVisibilityRequest(val *BucketVisibilityRequest) *NullableBucketVisibilityRequest {
	return &NullableBucketVisibilityRequest{value: val, isSet: true}
}

func (v NullableBucketVisibilityRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBucketVisibilityRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


