/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiCredentialCreated type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCredentialCreated{}

// ApiCredentialCreated struct for ApiCredentialCreated
type ApiCredentialCreated struct {
	Credential ApiCredential `json:"credential"`
	Key string `json:"key"`
}

type _ApiCredentialCreated ApiCredentialCreated

// NewApiCredentialCreated instantiates a new ApiCredentialCreated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCredentialCreated(credential ApiCredential, key string) *ApiCredentialCreated {
	this := ApiCredentialCreated{}
	this.Credential = credential
	this.Key = key
	return &this
}

// NewApiCredentialCreatedWithDefaults instantiates a new ApiCredentialCreated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCredentialCreatedWithDefaults() *ApiCredentialCreated {
	this := ApiCredentialCreated{}
	return &this
}

// GetCredential returns the Credential field value
func (o *ApiCredentialCreated) GetCredential() ApiCredential {
	if o == nil {
		var ret ApiCredential
		return ret
	}

	return o.Credential
}

// GetCredentialOk returns a tuple with the Credential field value
// and a boolean to check if the value has been set.
func (o *ApiCredentialCreated) GetCredentialOk() (*ApiCredential, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Credential, true
}

// SetCredential sets field value
func (o *ApiCredentialCreated) SetCredential(v ApiCredential) {
	o.Credential = v
}

// GetKey returns the Key field value
func (o *ApiCredentialCreated) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *ApiCredentialCreated) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *ApiCredentialCreated) SetKey(v string) {
	o.Key = v
}

func (o ApiCredentialCreated) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCredentialCreated) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["credential"] = o.Credential
	toSerialize["key"] = o.Key
	return toSerialize, nil
}

func (o *ApiCredentialCreated) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"credential",
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiCredentialCreated := _ApiCredentialCreated{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varApiCredentialCreated)

	if err != nil {
		return err
	}

	*o = ApiCredentialCreated(varApiCredentialCreated)

	return err
}

type NullableApiCredentialCreated struct {
	value *ApiCredentialCreated
	isSet bool
}

func (v NullableApiCredentialCreated) Get() *ApiCredentialCreated {
	return v.value
}

func (v *NullableApiCredentialCreated) Set(val *ApiCredentialCreated) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCredentialCreated) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCredentialCreated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCredentialCreated(val *ApiCredentialCreated) *NullableApiCredentialCreated {
	return &NullableApiCredentialCreated{value: val, isSet: true}
}

func (v NullableApiCredentialCreated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCredentialCreated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


