/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"fmt"
)

// StatusA57Enum * `pending` - Pending * `active` - Active * `provisioning` - Provisioning * `suspending` - Suspending * `suspended` - Suspended * `resuming` - Resuming * `cancelling` - Cancelling * `cancelled` - Cancelled * `terminating` - Terminating * `terminated` - Terminated * `failed` - Failed * `upgrading` - Upgrading
type StatusA57Enum string

// List of StatusA57Enum
const (
	STATUSA57ENUM_PENDING StatusA57Enum = "pending"
	STATUSA57ENUM_ACTIVE StatusA57Enum = "active"
	STATUSA57ENUM_PROVISIONING StatusA57Enum = "provisioning"
	STATUSA57ENUM_SUSPENDING StatusA57Enum = "suspending"
	STATUSA57ENUM_SUSPENDED StatusA57Enum = "suspended"
	STATUSA57ENUM_RESUMING StatusA57Enum = "resuming"
	STATUSA57ENUM_CANCELLING StatusA57Enum = "cancelling"
	STATUSA57ENUM_CANCELLED StatusA57Enum = "cancelled"
	STATUSA57ENUM_TERMINATING StatusA57Enum = "terminating"
	STATUSA57ENUM_TERMINATED StatusA57Enum = "terminated"
	STATUSA57ENUM_FAILED StatusA57Enum = "failed"
	STATUSA57ENUM_UPGRADING StatusA57Enum = "upgrading"
)

// All allowed values of StatusA57Enum enum
var AllowedStatusA57EnumEnumValues = []StatusA57Enum{
	"pending",
	"active",
	"provisioning",
	"suspending",
	"suspended",
	"resuming",
	"cancelling",
	"cancelled",
	"terminating",
	"terminated",
	"failed",
	"upgrading",
}

func (v *StatusA57Enum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := StatusA57Enum(value)
	for _, existing := range AllowedStatusA57EnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid StatusA57Enum", value)
}

// NewStatusA57EnumFromValue returns a pointer to a valid StatusA57Enum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewStatusA57EnumFromValue(v string) (*StatusA57Enum, error) {
	ev := StatusA57Enum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for StatusA57Enum: valid values are %v", v, AllowedStatusA57EnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v StatusA57Enum) IsValid() bool {
	for _, existing := range AllowedStatusA57EnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to StatusA57Enum value
func (v StatusA57Enum) Ptr() *StatusA57Enum {
	return &v
}

type NullableStatusA57Enum struct {
	value *StatusA57Enum
	isSet bool
}

func (v NullableStatusA57Enum) Get() *StatusA57Enum {
	return v.value
}

func (v *NullableStatusA57Enum) Set(val *StatusA57Enum) {
	v.value = val
	v.isSet = true
}

func (v NullableStatusA57Enum) IsSet() bool {
	return v.isSet
}

func (v *NullableStatusA57Enum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatusA57Enum(val *StatusA57Enum) *NullableStatusA57Enum {
	return &NullableStatusA57Enum{value: val, isSet: true}
}

func (v NullableStatusA57Enum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatusA57Enum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

