/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RescueExitQueued type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RescueExitQueued{}

// RescueExitQueued struct for RescueExitQueued
type RescueExitQueued struct {
	Queued bool `json:"queued"`
}

type _RescueExitQueued RescueExitQueued

// NewRescueExitQueued instantiates a new RescueExitQueued object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRescueExitQueued(queued bool) *RescueExitQueued {
	this := RescueExitQueued{}
	this.Queued = queued
	return &this
}

// NewRescueExitQueuedWithDefaults instantiates a new RescueExitQueued object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRescueExitQueuedWithDefaults() *RescueExitQueued {
	this := RescueExitQueued{}
	return &this
}

// GetQueued returns the Queued field value
func (o *RescueExitQueued) GetQueued() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Queued
}

// GetQueuedOk returns a tuple with the Queued field value
// and a boolean to check if the value has been set.
func (o *RescueExitQueued) GetQueuedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Queued, true
}

// SetQueued sets field value
func (o *RescueExitQueued) SetQueued(v bool) {
	o.Queued = v
}

func (o RescueExitQueued) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RescueExitQueued) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["queued"] = o.Queued
	return toSerialize, nil
}

func (o *RescueExitQueued) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"queued",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRescueExitQueued := _RescueExitQueued{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varRescueExitQueued)

	if err != nil {
		return err
	}

	*o = RescueExitQueued(varRescueExitQueued)

	return err
}

type NullableRescueExitQueued struct {
	value *RescueExitQueued
	isSet bool
}

func (v NullableRescueExitQueued) Get() *RescueExitQueued {
	return v.value
}

func (v *NullableRescueExitQueued) Set(val *RescueExitQueued) {
	v.value = val
	v.isSet = true
}

func (v NullableRescueExitQueued) IsSet() bool {
	return v.isSet
}

func (v *NullableRescueExitQueued) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRescueExitQueued(val *RescueExitQueued) *NullableRescueExitQueued {
	return &NullableRescueExitQueued{value: val, isSet: true}
}

func (v NullableRescueExitQueued) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRescueExitQueued) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


