/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChangeBillingCycleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangeBillingCycleResponse{}

// ChangeBillingCycleResponse struct for ChangeBillingCycleResponse
type ChangeBillingCycleResponse struct {
	Message string `json:"message"`
	BillingCycle string `json:"billing_cycle"`
}

type _ChangeBillingCycleResponse ChangeBillingCycleResponse

// NewChangeBillingCycleResponse instantiates a new ChangeBillingCycleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangeBillingCycleResponse(message string, billingCycle string) *ChangeBillingCycleResponse {
	this := ChangeBillingCycleResponse{}
	this.Message = message
	this.BillingCycle = billingCycle
	return &this
}

// NewChangeBillingCycleResponseWithDefaults instantiates a new ChangeBillingCycleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangeBillingCycleResponseWithDefaults() *ChangeBillingCycleResponse {
	this := ChangeBillingCycleResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *ChangeBillingCycleResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ChangeBillingCycleResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ChangeBillingCycleResponse) SetMessage(v string) {
	o.Message = v
}

// GetBillingCycle returns the BillingCycle field value
func (o *ChangeBillingCycleResponse) GetBillingCycle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BillingCycle
}

// GetBillingCycleOk returns a tuple with the BillingCycle field value
// and a boolean to check if the value has been set.
func (o *ChangeBillingCycleResponse) GetBillingCycleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingCycle, true
}

// SetBillingCycle sets field value
func (o *ChangeBillingCycleResponse) SetBillingCycle(v string) {
	o.BillingCycle = v
}

func (o ChangeBillingCycleResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangeBillingCycleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["billing_cycle"] = o.BillingCycle
	return toSerialize, nil
}

func (o *ChangeBillingCycleResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"billing_cycle",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChangeBillingCycleResponse := _ChangeBillingCycleResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChangeBillingCycleResponse)

	if err != nil {
		return err
	}

	*o = ChangeBillingCycleResponse(varChangeBillingCycleResponse)

	return err
}

type NullableChangeBillingCycleResponse struct {
	value *ChangeBillingCycleResponse
	isSet bool
}

func (v NullableChangeBillingCycleResponse) Get() *ChangeBillingCycleResponse {
	return v.value
}

func (v *NullableChangeBillingCycleResponse) Set(val *ChangeBillingCycleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeBillingCycleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeBillingCycleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeBillingCycleResponse(val *ChangeBillingCycleResponse) *NullableChangeBillingCycleResponse {
	return &NullableChangeBillingCycleResponse{value: val, isSet: true}
}

func (v NullableChangeBillingCycleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeBillingCycleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


