/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PowerManagement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PowerManagement{}

// PowerManagement struct for PowerManagement
type PowerManagement struct {
	Status string `json:"status"`
}

type _PowerManagement PowerManagement

// NewPowerManagement instantiates a new PowerManagement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPowerManagement(status string) *PowerManagement {
	this := PowerManagement{}
	this.Status = status
	return &this
}

// NewPowerManagementWithDefaults instantiates a new PowerManagement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPowerManagementWithDefaults() *PowerManagement {
	this := PowerManagement{}
	return &this
}

// GetStatus returns the Status field value
func (o *PowerManagement) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PowerManagement) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PowerManagement) SetStatus(v string) {
	o.Status = v
}

func (o PowerManagement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PowerManagement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *PowerManagement) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPowerManagement := _PowerManagement{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPowerManagement)

	if err != nil {
		return err
	}

	*o = PowerManagement(varPowerManagement)

	return err
}

type NullablePowerManagement struct {
	value *PowerManagement
	isSet bool
}

func (v NullablePowerManagement) Get() *PowerManagement {
	return v.value
}

func (v *NullablePowerManagement) Set(val *PowerManagement) {
	v.value = val
	v.isSet = true
}

func (v NullablePowerManagement) IsSet() bool {
	return v.isSet
}

func (v *NullablePowerManagement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePowerManagement(val *PowerManagement) *NullablePowerManagement {
	return &NullablePowerManagement{value: val, isSet: true}
}

func (v NullablePowerManagement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePowerManagement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


