/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConnectedVMsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectedVMsResponse{}

// ConnectedVMsResponse struct for ConnectedVMsResponse
type ConnectedVMsResponse struct {
	Vms []ConnectedVM `json:"vms"`
}

type _ConnectedVMsResponse ConnectedVMsResponse

// NewConnectedVMsResponse instantiates a new ConnectedVMsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectedVMsResponse(vms []ConnectedVM) *ConnectedVMsResponse {
	this := ConnectedVMsResponse{}
	this.Vms = vms
	return &this
}

// NewConnectedVMsResponseWithDefaults instantiates a new ConnectedVMsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectedVMsResponseWithDefaults() *ConnectedVMsResponse {
	this := ConnectedVMsResponse{}
	return &this
}

// GetVms returns the Vms field value
func (o *ConnectedVMsResponse) GetVms() []ConnectedVM {
	if o == nil {
		var ret []ConnectedVM
		return ret
	}

	return o.Vms
}

// GetVmsOk returns a tuple with the Vms field value
// and a boolean to check if the value has been set.
func (o *ConnectedVMsResponse) GetVmsOk() ([]ConnectedVM, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vms, true
}

// SetVms sets field value
func (o *ConnectedVMsResponse) SetVms(v []ConnectedVM) {
	o.Vms = v
}

func (o ConnectedVMsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectedVMsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["vms"] = o.Vms
	return toSerialize, nil
}

func (o *ConnectedVMsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"vms",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectedVMsResponse := _ConnectedVMsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConnectedVMsResponse)

	if err != nil {
		return err
	}

	*o = ConnectedVMsResponse(varConnectedVMsResponse)

	return err
}

type NullableConnectedVMsResponse struct {
	value *ConnectedVMsResponse
	isSet bool
}

func (v NullableConnectedVMsResponse) Get() *ConnectedVMsResponse {
	return v.value
}

func (v *NullableConnectedVMsResponse) Set(val *ConnectedVMsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectedVMsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectedVMsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectedVMsResponse(val *ConnectedVMsResponse) *NullableConnectedVMsResponse {
	return &NullableConnectedVMsResponse{value: val, isSet: true}
}

func (v NullableConnectedVMsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectedVMsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


