/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LBFirewallRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LBFirewallRule{}

// LBFirewallRule struct for LBFirewallRule
type LBFirewallRule struct {
	Id int32 `json:"id"`
	Direction *LBFirewallRuleDirectionEnum `json:"direction,omitempty"`
	Action *LBFirewallRuleActionEnum `json:"action,omitempty"`
	// tcp, udp, icmp, etc.
	Protocol *string `json:"protocol,omitempty"`
	// IP address or CIDR
	Source *string `json:"source,omitempty"`
	// Port or range (e.g., 1024-65535)
	Sport *string `json:"sport,omitempty"`
	// IP address or CIDR
	Destination *string `json:"destination,omitempty"`
	// Port or range (e.g., 80, 8000-9000)
	Dport *string `json:"dport,omitempty"`
	Comment *string `json:"comment,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	// Rule order (lower = higher priority)
	Position *int32 `json:"position,omitempty"`
	Created string `json:"created"`
	Updated string `json:"updated"`
}

type _LBFirewallRule LBFirewallRule

// NewLBFirewallRule instantiates a new LBFirewallRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLBFirewallRule(id int32, created string, updated string) *LBFirewallRule {
	this := LBFirewallRule{}
	this.Id = id
	this.Created = created
	this.Updated = updated
	return &this
}

// NewLBFirewallRuleWithDefaults instantiates a new LBFirewallRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLBFirewallRuleWithDefaults() *LBFirewallRule {
	this := LBFirewallRule{}
	return &this
}

// GetId returns the Id field value
func (o *LBFirewallRule) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LBFirewallRule) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LBFirewallRule) SetId(v int32) {
	o.Id = v
}

// GetDirection returns the Direction field value if set, zero value otherwise.
func (o *LBFirewallRule) GetDirection() LBFirewallRuleDirectionEnum {
	if o == nil || IsNil(o.Direction) {
		var ret LBFirewallRuleDirectionEnum
		return ret
	}
	return *o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LBFirewallRule) GetDirectionOk() (*LBFirewallRuleDirectionEnum, bool) {
	if o == nil || IsNil(o.Direction) {
		return nil, false
	}
	return o.Direction, true
}

// HasDirection returns a boolean if a field has been set.
func (o *LBFirewallRule) HasDirection() bool {
	if o != nil && !IsNil(o.Direction) {
		return true
	}

	return false
}

// SetDirection gets a reference to the given LBFirewallRuleDirectionEnum and assigns it to the Direction field.
func (o *LBFirewallRule) SetDirection(v LBFirewallRuleDirectionEnum) {
	o.Direction = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *LBFirewallRule) GetAction() LBFirewallRuleActionEnum {
	if o == nil || IsNil(o.Action) {
		var ret LBFirewallRuleActionEnum
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LBFirewallRule) GetActionOk() (*LBFirewallRuleActionEnum, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *LBFirewallRule) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given LBFirewallRuleActionEnum and assigns it to the Action field.
func (o *LBFirewallRule) SetAction(v LBFirewallRuleActionEnum) {
	o.Action = &v
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *LBFirewallRule) GetProtocol() string {
	if o == nil || IsNil(o.Protocol) {
		var ret string
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LBFirewallRule) GetProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.Protocol) {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *LBFirewallRule) HasProtocol() bool {
	if o != nil && !IsNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given string and assigns it to the Protocol field.
func (o *LBFirewallRule) SetProtocol(v string) {
	o.Protocol = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *LBFirewallRule) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LBFirewallRule) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *LBFirewallRule) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *LBFirewallRule) SetSource(v string) {
	o.Source = &v
}

// GetSport returns the Sport field value if set, zero value otherwise.
func (o *LBFirewallRule) GetSport() string {
	if o == nil || IsNil(o.Sport) {
		var ret string
		return ret
	}
	return *o.Sport
}

// GetSportOk returns a tuple with the Sport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LBFirewallRule) GetSportOk() (*string, bool) {
	if o == nil || IsNil(o.Sport) {
		return nil, false
	}
	return o.Sport, true
}

// HasSport returns a boolean if a field has been set.
func (o *LBFirewallRule) HasSport() bool {
	if o != nil && !IsNil(o.Sport) {
		return true
	}

	return false
}

// SetSport gets a reference to the given string and assigns it to the Sport field.
func (o *LBFirewallRule) SetSport(v string) {
	o.Sport = &v
}

// GetDestination returns the Destination field value if set, zero value otherwise.
func (o *LBFirewallRule) GetDestination() string {
	if o == nil || IsNil(o.Destination) {
		var ret string
		return ret
	}
	return *o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LBFirewallRule) GetDestinationOk() (*string, bool) {
	if o == nil || IsNil(o.Destination) {
		return nil, false
	}
	return o.Destination, true
}

// HasDestination returns a boolean if a field has been set.
func (o *LBFirewallRule) HasDestination() bool {
	if o != nil && !IsNil(o.Destination) {
		return true
	}

	return false
}

// SetDestination gets a reference to the given string and assigns it to the Destination field.
func (o *LBFirewallRule) SetDestination(v string) {
	o.Destination = &v
}

// GetDport returns the Dport field value if set, zero value otherwise.
func (o *LBFirewallRule) GetDport() string {
	if o == nil || IsNil(o.Dport) {
		var ret string
		return ret
	}
	return *o.Dport
}

// GetDportOk returns a tuple with the Dport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LBFirewallRule) GetDportOk() (*string, bool) {
	if o == nil || IsNil(o.Dport) {
		return nil, false
	}
	return o.Dport, true
}

// HasDport returns a boolean if a field has been set.
func (o *LBFirewallRule) HasDport() bool {
	if o != nil && !IsNil(o.Dport) {
		return true
	}

	return false
}

// SetDport gets a reference to the given string and assigns it to the Dport field.
func (o *LBFirewallRule) SetDport(v string) {
	o.Dport = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *LBFirewallRule) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LBFirewallRule) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *LBFirewallRule) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *LBFirewallRule) SetComment(v string) {
	o.Comment = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *LBFirewallRule) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LBFirewallRule) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *LBFirewallRule) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *LBFirewallRule) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *LBFirewallRule) GetPosition() int32 {
	if o == nil || IsNil(o.Position) {
		var ret int32
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LBFirewallRule) GetPositionOk() (*int32, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *LBFirewallRule) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int32 and assigns it to the Position field.
func (o *LBFirewallRule) SetPosition(v int32) {
	o.Position = &v
}

// GetCreated returns the Created field value
func (o *LBFirewallRule) GetCreated() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *LBFirewallRule) GetCreatedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *LBFirewallRule) SetCreated(v string) {
	o.Created = v
}

// GetUpdated returns the Updated field value
func (o *LBFirewallRule) GetUpdated() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *LBFirewallRule) GetUpdatedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *LBFirewallRule) SetUpdated(v string) {
	o.Updated = v
}

func (o LBFirewallRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LBFirewallRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Direction) {
		toSerialize["direction"] = o.Direction
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.Protocol) {
		toSerialize["protocol"] = o.Protocol
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Sport) {
		toSerialize["sport"] = o.Sport
	}
	if !IsNil(o.Destination) {
		toSerialize["destination"] = o.Destination
	}
	if !IsNil(o.Dport) {
		toSerialize["dport"] = o.Dport
	}
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	toSerialize["created"] = o.Created
	toSerialize["updated"] = o.Updated
	return toSerialize, nil
}

func (o *LBFirewallRule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"created",
		"updated",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLBFirewallRule := _LBFirewallRule{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varLBFirewallRule)

	if err != nil {
		return err
	}

	*o = LBFirewallRule(varLBFirewallRule)

	return err
}

type NullableLBFirewallRule struct {
	value *LBFirewallRule
	isSet bool
}

func (v NullableLBFirewallRule) Get() *LBFirewallRule {
	return v.value
}

func (v *NullableLBFirewallRule) Set(val *LBFirewallRule) {
	v.value = val
	v.isSet = true
}

func (v NullableLBFirewallRule) IsSet() bool {
	return v.isSet
}

func (v *NullableLBFirewallRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLBFirewallRule(val *LBFirewallRule) *NullableLBFirewallRule {
	return &NullableLBFirewallRule{value: val, isSet: true}
}

func (v NullableLBFirewallRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLBFirewallRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


