/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmailMessageList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailMessageList{}

// EmailMessageList struct for EmailMessageList
type EmailMessageList struct {
	Results []EmailMessageSummary `json:"results"`
	Count int32 `json:"count"`
	Page int32 `json:"page"`
	PerPage int32 `json:"per_page"`
}

type _EmailMessageList EmailMessageList

// NewEmailMessageList instantiates a new EmailMessageList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailMessageList(results []EmailMessageSummary, count int32, page int32, perPage int32) *EmailMessageList {
	this := EmailMessageList{}
	this.Results = results
	this.Count = count
	this.Page = page
	this.PerPage = perPage
	return &this
}

// NewEmailMessageListWithDefaults instantiates a new EmailMessageList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailMessageListWithDefaults() *EmailMessageList {
	this := EmailMessageList{}
	return &this
}

// GetResults returns the Results field value
func (o *EmailMessageList) GetResults() []EmailMessageSummary {
	if o == nil {
		var ret []EmailMessageSummary
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *EmailMessageList) GetResultsOk() ([]EmailMessageSummary, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *EmailMessageList) SetResults(v []EmailMessageSummary) {
	o.Results = v
}

// GetCount returns the Count field value
func (o *EmailMessageList) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *EmailMessageList) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *EmailMessageList) SetCount(v int32) {
	o.Count = v
}

// GetPage returns the Page field value
func (o *EmailMessageList) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *EmailMessageList) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *EmailMessageList) SetPage(v int32) {
	o.Page = v
}

// GetPerPage returns the PerPage field value
func (o *EmailMessageList) GetPerPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value
// and a boolean to check if the value has been set.
func (o *EmailMessageList) GetPerPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PerPage, true
}

// SetPerPage sets field value
func (o *EmailMessageList) SetPerPage(v int32) {
	o.PerPage = v
}

func (o EmailMessageList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailMessageList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["results"] = o.Results
	toSerialize["count"] = o.Count
	toSerialize["page"] = o.Page
	toSerialize["per_page"] = o.PerPage
	return toSerialize, nil
}

func (o *EmailMessageList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"results",
		"count",
		"page",
		"per_page",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailMessageList := _EmailMessageList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varEmailMessageList)

	if err != nil {
		return err
	}

	*o = EmailMessageList(varEmailMessageList)

	return err
}

type NullableEmailMessageList struct {
	value *EmailMessageList
	isSet bool
}

func (v NullableEmailMessageList) Get() *EmailMessageList {
	return v.value
}

func (v *NullableEmailMessageList) Set(val *EmailMessageList) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailMessageList) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailMessageList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailMessageList(val *EmailMessageList) *NullableEmailMessageList {
	return &NullableEmailMessageList{value: val, isSet: true}
}

func (v NullableEmailMessageList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailMessageList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


