/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AttachIPv4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttachIPv4{}

// AttachIPv4 struct for AttachIPv4
type AttachIPv4 struct {
	// ID or slug
	Ipv4 string `json:"ipv4"`
}

type _AttachIPv4 AttachIPv4

// NewAttachIPv4 instantiates a new AttachIPv4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttachIPv4(ipv4 string) *AttachIPv4 {
	this := AttachIPv4{}
	this.Ipv4 = ipv4
	return &this
}

// NewAttachIPv4WithDefaults instantiates a new AttachIPv4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttachIPv4WithDefaults() *AttachIPv4 {
	this := AttachIPv4{}
	return &this
}

// GetIpv4 returns the Ipv4 field value
func (o *AttachIPv4) GetIpv4() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ipv4
}

// GetIpv4Ok returns a tuple with the Ipv4 field value
// and a boolean to check if the value has been set.
func (o *AttachIPv4) GetIpv4Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ipv4, true
}

// SetIpv4 sets field value
func (o *AttachIPv4) SetIpv4(v string) {
	o.Ipv4 = v
}

func (o AttachIPv4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttachIPv4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ipv4"] = o.Ipv4
	return toSerialize, nil
}

func (o *AttachIPv4) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ipv4",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAttachIPv4 := _AttachIPv4{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAttachIPv4)

	if err != nil {
		return err
	}

	*o = AttachIPv4(varAttachIPv4)

	return err
}

type NullableAttachIPv4 struct {
	value *AttachIPv4
	isSet bool
}

func (v NullableAttachIPv4) Get() *AttachIPv4 {
	return v.value
}

func (v *NullableAttachIPv4) Set(val *AttachIPv4) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachIPv4) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachIPv4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachIPv4(val *AttachIPv4) *NullableAttachIPv4 {
	return &NullableAttachIPv4{value: val, isSet: true}
}

func (v NullableAttachIPv4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachIPv4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


