/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InboundRouteWriteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InboundRouteWriteResponse{}

// InboundRouteWriteResponse struct for InboundRouteWriteResponse
type InboundRouteWriteResponse struct {
	Id int32 `json:"id"`
	Domain int32 `json:"domain"`
	Pattern string `json:"pattern"`
	Mode ModeEnum `json:"mode"`
	WebhookUrl *string `json:"webhook_url,omitempty"`
	ForwardTo *string `json:"forward_to,omitempty"`
	Active *bool `json:"active,omitempty"`
	CreatedAt string `json:"created_at"`
	WebhookSecret *string `json:"webhook_secret,omitempty"`
}

type _InboundRouteWriteResponse InboundRouteWriteResponse

// NewInboundRouteWriteResponse instantiates a new InboundRouteWriteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInboundRouteWriteResponse(id int32, domain int32, pattern string, mode ModeEnum, createdAt string) *InboundRouteWriteResponse {
	this := InboundRouteWriteResponse{}
	this.Id = id
	this.Domain = domain
	this.Pattern = pattern
	this.Mode = mode
	this.CreatedAt = createdAt
	return &this
}

// NewInboundRouteWriteResponseWithDefaults instantiates a new InboundRouteWriteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInboundRouteWriteResponseWithDefaults() *InboundRouteWriteResponse {
	this := InboundRouteWriteResponse{}
	return &this
}

// GetId returns the Id field value
func (o *InboundRouteWriteResponse) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InboundRouteWriteResponse) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InboundRouteWriteResponse) SetId(v int32) {
	o.Id = v
}

// GetDomain returns the Domain field value
func (o *InboundRouteWriteResponse) GetDomain() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *InboundRouteWriteResponse) GetDomainOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *InboundRouteWriteResponse) SetDomain(v int32) {
	o.Domain = v
}

// GetPattern returns the Pattern field value
func (o *InboundRouteWriteResponse) GetPattern() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pattern
}

// GetPatternOk returns a tuple with the Pattern field value
// and a boolean to check if the value has been set.
func (o *InboundRouteWriteResponse) GetPatternOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pattern, true
}

// SetPattern sets field value
func (o *InboundRouteWriteResponse) SetPattern(v string) {
	o.Pattern = v
}

// GetMode returns the Mode field value
func (o *InboundRouteWriteResponse) GetMode() ModeEnum {
	if o == nil {
		var ret ModeEnum
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *InboundRouteWriteResponse) GetModeOk() (*ModeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *InboundRouteWriteResponse) SetMode(v ModeEnum) {
	o.Mode = v
}

// GetWebhookUrl returns the WebhookUrl field value if set, zero value otherwise.
func (o *InboundRouteWriteResponse) GetWebhookUrl() string {
	if o == nil || IsNil(o.WebhookUrl) {
		var ret string
		return ret
	}
	return *o.WebhookUrl
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InboundRouteWriteResponse) GetWebhookUrlOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookUrl) {
		return nil, false
	}
	return o.WebhookUrl, true
}

// HasWebhookUrl returns a boolean if a field has been set.
func (o *InboundRouteWriteResponse) HasWebhookUrl() bool {
	if o != nil && !IsNil(o.WebhookUrl) {
		return true
	}

	return false
}

// SetWebhookUrl gets a reference to the given string and assigns it to the WebhookUrl field.
func (o *InboundRouteWriteResponse) SetWebhookUrl(v string) {
	o.WebhookUrl = &v
}

// GetForwardTo returns the ForwardTo field value if set, zero value otherwise.
func (o *InboundRouteWriteResponse) GetForwardTo() string {
	if o == nil || IsNil(o.ForwardTo) {
		var ret string
		return ret
	}
	return *o.ForwardTo
}

// GetForwardToOk returns a tuple with the ForwardTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InboundRouteWriteResponse) GetForwardToOk() (*string, bool) {
	if o == nil || IsNil(o.ForwardTo) {
		return nil, false
	}
	return o.ForwardTo, true
}

// HasForwardTo returns a boolean if a field has been set.
func (o *InboundRouteWriteResponse) HasForwardTo() bool {
	if o != nil && !IsNil(o.ForwardTo) {
		return true
	}

	return false
}

// SetForwardTo gets a reference to the given string and assigns it to the ForwardTo field.
func (o *InboundRouteWriteResponse) SetForwardTo(v string) {
	o.ForwardTo = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *InboundRouteWriteResponse) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InboundRouteWriteResponse) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *InboundRouteWriteResponse) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *InboundRouteWriteResponse) SetActive(v bool) {
	o.Active = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *InboundRouteWriteResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *InboundRouteWriteResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *InboundRouteWriteResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetWebhookSecret returns the WebhookSecret field value if set, zero value otherwise.
func (o *InboundRouteWriteResponse) GetWebhookSecret() string {
	if o == nil || IsNil(o.WebhookSecret) {
		var ret string
		return ret
	}
	return *o.WebhookSecret
}

// GetWebhookSecretOk returns a tuple with the WebhookSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InboundRouteWriteResponse) GetWebhookSecretOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookSecret) {
		return nil, false
	}
	return o.WebhookSecret, true
}

// HasWebhookSecret returns a boolean if a field has been set.
func (o *InboundRouteWriteResponse) HasWebhookSecret() bool {
	if o != nil && !IsNil(o.WebhookSecret) {
		return true
	}

	return false
}

// SetWebhookSecret gets a reference to the given string and assigns it to the WebhookSecret field.
func (o *InboundRouteWriteResponse) SetWebhookSecret(v string) {
	o.WebhookSecret = &v
}

func (o InboundRouteWriteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InboundRouteWriteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["domain"] = o.Domain
	toSerialize["pattern"] = o.Pattern
	toSerialize["mode"] = o.Mode
	if !IsNil(o.WebhookUrl) {
		toSerialize["webhook_url"] = o.WebhookUrl
	}
	if !IsNil(o.ForwardTo) {
		toSerialize["forward_to"] = o.ForwardTo
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.WebhookSecret) {
		toSerialize["webhook_secret"] = o.WebhookSecret
	}
	return toSerialize, nil
}

func (o *InboundRouteWriteResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"domain",
		"pattern",
		"mode",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInboundRouteWriteResponse := _InboundRouteWriteResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varInboundRouteWriteResponse)

	if err != nil {
		return err
	}

	*o = InboundRouteWriteResponse(varInboundRouteWriteResponse)

	return err
}

type NullableInboundRouteWriteResponse struct {
	value *InboundRouteWriteResponse
	isSet bool
}

func (v NullableInboundRouteWriteResponse) Get() *InboundRouteWriteResponse {
	return v.value
}

func (v *NullableInboundRouteWriteResponse) Set(val *InboundRouteWriteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInboundRouteWriteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInboundRouteWriteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInboundRouteWriteResponse(val *InboundRouteWriteResponse) *NullableInboundRouteWriteResponse {
	return &NullableInboundRouteWriteResponse{value: val, isSet: true}
}

func (v NullableInboundRouteWriteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInboundRouteWriteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


