/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"fmt"
)

// LBFirewallRuleDirectionEnum * `in` - Inbound * `out` - Outbound
type LBFirewallRuleDirectionEnum string

// List of LBFirewallRuleDirectionEnum
const (
	LBFIREWALLRULEDIRECTIONENUM_IN LBFirewallRuleDirectionEnum = "in"
	LBFIREWALLRULEDIRECTIONENUM_OUT LBFirewallRuleDirectionEnum = "out"
)

// All allowed values of LBFirewallRuleDirectionEnum enum
var AllowedLBFirewallRuleDirectionEnumEnumValues = []LBFirewallRuleDirectionEnum{
	"in",
	"out",
}

func (v *LBFirewallRuleDirectionEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LBFirewallRuleDirectionEnum(value)
	for _, existing := range AllowedLBFirewallRuleDirectionEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LBFirewallRuleDirectionEnum", value)
}

// NewLBFirewallRuleDirectionEnumFromValue returns a pointer to a valid LBFirewallRuleDirectionEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLBFirewallRuleDirectionEnumFromValue(v string) (*LBFirewallRuleDirectionEnum, error) {
	ev := LBFirewallRuleDirectionEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LBFirewallRuleDirectionEnum: valid values are %v", v, AllowedLBFirewallRuleDirectionEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LBFirewallRuleDirectionEnum) IsValid() bool {
	for _, existing := range AllowedLBFirewallRuleDirectionEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LBFirewallRuleDirectionEnum value
func (v LBFirewallRuleDirectionEnum) Ptr() *LBFirewallRuleDirectionEnum {
	return &v
}

type NullableLBFirewallRuleDirectionEnum struct {
	value *LBFirewallRuleDirectionEnum
	isSet bool
}

func (v NullableLBFirewallRuleDirectionEnum) Get() *LBFirewallRuleDirectionEnum {
	return v.value
}

func (v *NullableLBFirewallRuleDirectionEnum) Set(val *LBFirewallRuleDirectionEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableLBFirewallRuleDirectionEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableLBFirewallRuleDirectionEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLBFirewallRuleDirectionEnum(val *LBFirewallRuleDirectionEnum) *NullableLBFirewallRuleDirectionEnum {
	return &NullableLBFirewallRuleDirectionEnum{value: val, isSet: true}
}

func (v NullableLBFirewallRuleDirectionEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLBFirewallRuleDirectionEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

