/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
)

// checks if the PatchedDomainRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedDomainRequest{}

// PatchedDomainRequest struct for PatchedDomainRequest
type PatchedDomainRequest struct {
	// List of 2-5 name-servers separated by comma.
	Nameservers *string `json:"nameservers,omitempty"`
}

// NewPatchedDomainRequest instantiates a new PatchedDomainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedDomainRequest() *PatchedDomainRequest {
	this := PatchedDomainRequest{}
	return &this
}

// NewPatchedDomainRequestWithDefaults instantiates a new PatchedDomainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedDomainRequestWithDefaults() *PatchedDomainRequest {
	this := PatchedDomainRequest{}
	return &this
}

// GetNameservers returns the Nameservers field value if set, zero value otherwise.
func (o *PatchedDomainRequest) GetNameservers() string {
	if o == nil || IsNil(o.Nameservers) {
		var ret string
		return ret
	}
	return *o.Nameservers
}

// GetNameserversOk returns a tuple with the Nameservers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDomainRequest) GetNameserversOk() (*string, bool) {
	if o == nil || IsNil(o.Nameservers) {
		return nil, false
	}
	return o.Nameservers, true
}

// HasNameservers returns a boolean if a field has been set.
func (o *PatchedDomainRequest) HasNameservers() bool {
	if o != nil && !IsNil(o.Nameservers) {
		return true
	}

	return false
}

// SetNameservers gets a reference to the given string and assigns it to the Nameservers field.
func (o *PatchedDomainRequest) SetNameservers(v string) {
	o.Nameservers = &v
}

func (o PatchedDomainRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedDomainRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Nameservers) {
		toSerialize["nameservers"] = o.Nameservers
	}
	return toSerialize, nil
}

type NullablePatchedDomainRequest struct {
	value *PatchedDomainRequest
	isSet bool
}

func (v NullablePatchedDomainRequest) Get() *PatchedDomainRequest {
	return v.value
}

func (v *NullablePatchedDomainRequest) Set(val *PatchedDomainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedDomainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedDomainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedDomainRequest(val *PatchedDomainRequest) *NullablePatchedDomainRequest {
	return &NullablePatchedDomainRequest{value: val, isSet: true}
}

func (v NullablePatchedDomainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedDomainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


