/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PowerManagementRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PowerManagementRequest{}

// PowerManagementRequest struct for PowerManagementRequest
type PowerManagementRequest struct {
	Action PowerManagementRequestActionEnum `json:"action"`
}

type _PowerManagementRequest PowerManagementRequest

// NewPowerManagementRequest instantiates a new PowerManagementRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPowerManagementRequest(action PowerManagementRequestActionEnum) *PowerManagementRequest {
	this := PowerManagementRequest{}
	this.Action = action
	return &this
}

// NewPowerManagementRequestWithDefaults instantiates a new PowerManagementRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPowerManagementRequestWithDefaults() *PowerManagementRequest {
	this := PowerManagementRequest{}
	return &this
}

// GetAction returns the Action field value
func (o *PowerManagementRequest) GetAction() PowerManagementRequestActionEnum {
	if o == nil {
		var ret PowerManagementRequestActionEnum
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *PowerManagementRequest) GetActionOk() (*PowerManagementRequestActionEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *PowerManagementRequest) SetAction(v PowerManagementRequestActionEnum) {
	o.Action = v
}

func (o PowerManagementRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PowerManagementRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	return toSerialize, nil
}

func (o *PowerManagementRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPowerManagementRequest := _PowerManagementRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPowerManagementRequest)

	if err != nil {
		return err
	}

	*o = PowerManagementRequest(varPowerManagementRequest)

	return err
}

type NullablePowerManagementRequest struct {
	value *PowerManagementRequest
	isSet bool
}

func (v NullablePowerManagementRequest) Get() *PowerManagementRequest {
	return v.value
}

func (v *NullablePowerManagementRequest) Set(val *PowerManagementRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePowerManagementRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePowerManagementRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePowerManagementRequest(val *PowerManagementRequest) *NullablePowerManagementRequest {
	return &NullablePowerManagementRequest{value: val, isSet: true}
}

func (v NullablePowerManagementRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePowerManagementRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


