/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"os"
	"bytes"
	"fmt"
)

// checks if the TicketCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TicketCreateRequest{}

// TicketCreateRequest struct for TicketCreateRequest
type TicketCreateRequest struct {
	Subject string `json:"subject"`
	Department int32 `json:"department"`
	Priority *TicketCreatePriorityEnum `json:"priority,omitempty"`
	ServiceId NullableInt32 `json:"service_id,omitempty"`
	Message string `json:"message"`
	Attachment **os.File `json:"attachment,omitempty"`
}

type _TicketCreateRequest TicketCreateRequest

// NewTicketCreateRequest instantiates a new TicketCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTicketCreateRequest(subject string, department int32, message string) *TicketCreateRequest {
	this := TicketCreateRequest{}
	this.Subject = subject
	this.Department = department
	var priority TicketCreatePriorityEnum = TICKETCREATEPRIORITYENUM_LOW
	this.Priority = &priority
	this.Message = message
	return &this
}

// NewTicketCreateRequestWithDefaults instantiates a new TicketCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTicketCreateRequestWithDefaults() *TicketCreateRequest {
	this := TicketCreateRequest{}
	var priority TicketCreatePriorityEnum = TICKETCREATEPRIORITYENUM_LOW
	this.Priority = &priority
	return &this
}

// GetSubject returns the Subject field value
func (o *TicketCreateRequest) GetSubject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *TicketCreateRequest) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *TicketCreateRequest) SetSubject(v string) {
	o.Subject = v
}

// GetDepartment returns the Department field value
func (o *TicketCreateRequest) GetDepartment() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Department
}

// GetDepartmentOk returns a tuple with the Department field value
// and a boolean to check if the value has been set.
func (o *TicketCreateRequest) GetDepartmentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Department, true
}

// SetDepartment sets field value
func (o *TicketCreateRequest) SetDepartment(v int32) {
	o.Department = v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *TicketCreateRequest) GetPriority() TicketCreatePriorityEnum {
	if o == nil || IsNil(o.Priority) {
		var ret TicketCreatePriorityEnum
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TicketCreateRequest) GetPriorityOk() (*TicketCreatePriorityEnum, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *TicketCreateRequest) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given TicketCreatePriorityEnum and assigns it to the Priority field.
func (o *TicketCreateRequest) SetPriority(v TicketCreatePriorityEnum) {
	o.Priority = &v
}

// GetServiceId returns the ServiceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TicketCreateRequest) GetServiceId() int32 {
	if o == nil || IsNil(o.ServiceId.Get()) {
		var ret int32
		return ret
	}
	return *o.ServiceId.Get()
}

// GetServiceIdOk returns a tuple with the ServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TicketCreateRequest) GetServiceIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServiceId.Get(), o.ServiceId.IsSet()
}

// HasServiceId returns a boolean if a field has been set.
func (o *TicketCreateRequest) HasServiceId() bool {
	if o != nil && o.ServiceId.IsSet() {
		return true
	}

	return false
}

// SetServiceId gets a reference to the given NullableInt32 and assigns it to the ServiceId field.
func (o *TicketCreateRequest) SetServiceId(v int32) {
	o.ServiceId.Set(&v)
}
// SetServiceIdNil sets the value for ServiceId to be an explicit nil
func (o *TicketCreateRequest) SetServiceIdNil() {
	o.ServiceId.Set(nil)
}

// UnsetServiceId ensures that no value is present for ServiceId, not even an explicit nil
func (o *TicketCreateRequest) UnsetServiceId() {
	o.ServiceId.Unset()
}

// GetMessage returns the Message field value
func (o *TicketCreateRequest) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *TicketCreateRequest) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *TicketCreateRequest) SetMessage(v string) {
	o.Message = v
}

// GetAttachment returns the Attachment field value if set, zero value otherwise.
func (o *TicketCreateRequest) GetAttachment() *os.File {
	if o == nil || IsNil(o.Attachment) {
		var ret *os.File
		return ret
	}
	return *o.Attachment
}

// GetAttachmentOk returns a tuple with the Attachment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TicketCreateRequest) GetAttachmentOk() (**os.File, bool) {
	if o == nil || IsNil(o.Attachment) {
		return nil, false
	}
	return o.Attachment, true
}

// HasAttachment returns a boolean if a field has been set.
func (o *TicketCreateRequest) HasAttachment() bool {
	if o != nil && !IsNil(o.Attachment) {
		return true
	}

	return false
}

// SetAttachment gets a reference to the given *os.File and assigns it to the Attachment field.
func (o *TicketCreateRequest) SetAttachment(v *os.File) {
	o.Attachment = &v
}

func (o TicketCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TicketCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subject"] = o.Subject
	toSerialize["department"] = o.Department
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if o.ServiceId.IsSet() {
		toSerialize["service_id"] = o.ServiceId.Get()
	}
	toSerialize["message"] = o.Message
	if !IsNil(o.Attachment) {
		toSerialize["attachment"] = o.Attachment
	}
	return toSerialize, nil
}

func (o *TicketCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subject",
		"department",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTicketCreateRequest := _TicketCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varTicketCreateRequest)

	if err != nil {
		return err
	}

	*o = TicketCreateRequest(varTicketCreateRequest)

	return err
}

type NullableTicketCreateRequest struct {
	value *TicketCreateRequest
	isSet bool
}

func (v NullableTicketCreateRequest) Get() *TicketCreateRequest {
	return v.value
}

func (v *NullableTicketCreateRequest) Set(val *TicketCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTicketCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTicketCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTicketCreateRequest(val *TicketCreateRequest) *NullableTicketCreateRequest {
	return &NullableTicketCreateRequest{value: val, isSet: true}
}

func (v NullableTicketCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTicketCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


