/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmailStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailStats{}

// EmailStats struct for EmailStats
type EmailStats struct {
	Start string `json:"start"`
	End string `json:"end"`
	Totals StatsTotals `json:"totals"`
	Days []StatsDay `json:"days"`
	Reputation EmailReputation `json:"reputation"`
}

type _EmailStats EmailStats

// NewEmailStats instantiates a new EmailStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailStats(start string, end string, totals StatsTotals, days []StatsDay, reputation EmailReputation) *EmailStats {
	this := EmailStats{}
	this.Start = start
	this.End = end
	this.Totals = totals
	this.Days = days
	this.Reputation = reputation
	return &this
}

// NewEmailStatsWithDefaults instantiates a new EmailStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailStatsWithDefaults() *EmailStats {
	this := EmailStats{}
	return &this
}

// GetStart returns the Start field value
func (o *EmailStats) GetStart() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *EmailStats) GetStartOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *EmailStats) SetStart(v string) {
	o.Start = v
}

// GetEnd returns the End field value
func (o *EmailStats) GetEnd() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *EmailStats) GetEndOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *EmailStats) SetEnd(v string) {
	o.End = v
}

// GetTotals returns the Totals field value
func (o *EmailStats) GetTotals() StatsTotals {
	if o == nil {
		var ret StatsTotals
		return ret
	}

	return o.Totals
}

// GetTotalsOk returns a tuple with the Totals field value
// and a boolean to check if the value has been set.
func (o *EmailStats) GetTotalsOk() (*StatsTotals, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Totals, true
}

// SetTotals sets field value
func (o *EmailStats) SetTotals(v StatsTotals) {
	o.Totals = v
}

// GetDays returns the Days field value
func (o *EmailStats) GetDays() []StatsDay {
	if o == nil {
		var ret []StatsDay
		return ret
	}

	return o.Days
}

// GetDaysOk returns a tuple with the Days field value
// and a boolean to check if the value has been set.
func (o *EmailStats) GetDaysOk() ([]StatsDay, bool) {
	if o == nil {
		return nil, false
	}
	return o.Days, true
}

// SetDays sets field value
func (o *EmailStats) SetDays(v []StatsDay) {
	o.Days = v
}

// GetReputation returns the Reputation field value
func (o *EmailStats) GetReputation() EmailReputation {
	if o == nil {
		var ret EmailReputation
		return ret
	}

	return o.Reputation
}

// GetReputationOk returns a tuple with the Reputation field value
// and a boolean to check if the value has been set.
func (o *EmailStats) GetReputationOk() (*EmailReputation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reputation, true
}

// SetReputation sets field value
func (o *EmailStats) SetReputation(v EmailReputation) {
	o.Reputation = v
}

func (o EmailStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["start"] = o.Start
	toSerialize["end"] = o.End
	toSerialize["totals"] = o.Totals
	toSerialize["days"] = o.Days
	toSerialize["reputation"] = o.Reputation
	return toSerialize, nil
}

func (o *EmailStats) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"start",
		"end",
		"totals",
		"days",
		"reputation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailStats := _EmailStats{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varEmailStats)

	if err != nil {
		return err
	}

	*o = EmailStats(varEmailStats)

	return err
}

type NullableEmailStats struct {
	value *EmailStats
	isSet bool
}

func (v NullableEmailStats) Get() *EmailStats {
	return v.value
}

func (v *NullableEmailStats) Set(val *EmailStats) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailStats) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailStats(val *EmailStats) *NullableEmailStats {
	return &NullableEmailStats{value: val, isSet: true}
}

func (v NullableEmailStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


