/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CLISessionCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CLISessionCreateResponse{}

// CLISessionCreateResponse struct for CLISessionCreateResponse
type CLISessionCreateResponse struct {
	SessionId string `json:"session_id"`
	VerificationUrl string `json:"verification_url"`
	ExpiresAt string `json:"expires_at"`
	// Recommended polling interval in seconds
	PollInterval int32 `json:"poll_interval"`
}

type _CLISessionCreateResponse CLISessionCreateResponse

// NewCLISessionCreateResponse instantiates a new CLISessionCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCLISessionCreateResponse(sessionId string, verificationUrl string, expiresAt string, pollInterval int32) *CLISessionCreateResponse {
	this := CLISessionCreateResponse{}
	this.SessionId = sessionId
	this.VerificationUrl = verificationUrl
	this.ExpiresAt = expiresAt
	this.PollInterval = pollInterval
	return &this
}

// NewCLISessionCreateResponseWithDefaults instantiates a new CLISessionCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCLISessionCreateResponseWithDefaults() *CLISessionCreateResponse {
	this := CLISessionCreateResponse{}
	return &this
}

// GetSessionId returns the SessionId field value
func (o *CLISessionCreateResponse) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *CLISessionCreateResponse) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *CLISessionCreateResponse) SetSessionId(v string) {
	o.SessionId = v
}

// GetVerificationUrl returns the VerificationUrl field value
func (o *CLISessionCreateResponse) GetVerificationUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerificationUrl
}

// GetVerificationUrlOk returns a tuple with the VerificationUrl field value
// and a boolean to check if the value has been set.
func (o *CLISessionCreateResponse) GetVerificationUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerificationUrl, true
}

// SetVerificationUrl sets field value
func (o *CLISessionCreateResponse) SetVerificationUrl(v string) {
	o.VerificationUrl = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *CLISessionCreateResponse) GetExpiresAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *CLISessionCreateResponse) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *CLISessionCreateResponse) SetExpiresAt(v string) {
	o.ExpiresAt = v
}

// GetPollInterval returns the PollInterval field value
func (o *CLISessionCreateResponse) GetPollInterval() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PollInterval
}

// GetPollIntervalOk returns a tuple with the PollInterval field value
// and a boolean to check if the value has been set.
func (o *CLISessionCreateResponse) GetPollIntervalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PollInterval, true
}

// SetPollInterval sets field value
func (o *CLISessionCreateResponse) SetPollInterval(v int32) {
	o.PollInterval = v
}

func (o CLISessionCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CLISessionCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["session_id"] = o.SessionId
	toSerialize["verification_url"] = o.VerificationUrl
	toSerialize["expires_at"] = o.ExpiresAt
	toSerialize["poll_interval"] = o.PollInterval
	return toSerialize, nil
}

func (o *CLISessionCreateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"session_id",
		"verification_url",
		"expires_at",
		"poll_interval",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCLISessionCreateResponse := _CLISessionCreateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCLISessionCreateResponse)

	if err != nil {
		return err
	}

	*o = CLISessionCreateResponse(varCLISessionCreateResponse)

	return err
}

type NullableCLISessionCreateResponse struct {
	value *CLISessionCreateResponse
	isSet bool
}

func (v NullableCLISessionCreateResponse) Get() *CLISessionCreateResponse {
	return v.value
}

func (v *NullableCLISessionCreateResponse) Set(val *CLISessionCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCLISessionCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCLISessionCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCLISessionCreateResponse(val *CLISessionCreateResponse) *NullableCLISessionCreateResponse {
	return &NullableCLISessionCreateResponse{value: val, isSet: true}
}

func (v NullableCLISessionCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCLISessionCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


