/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FirewallRulesSet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FirewallRulesSet{}

// FirewallRulesSet struct for FirewallRulesSet
type FirewallRulesSet struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	Status FirewallRulesSetStatusEnum `json:"status"`
	Rules []FirewallRule `json:"rules"`
	// used with free tier vm
	ReadOnly bool `json:"read_only"`
}

type _FirewallRulesSet FirewallRulesSet

// NewFirewallRulesSet instantiates a new FirewallRulesSet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirewallRulesSet(id int32, name string, status FirewallRulesSetStatusEnum, rules []FirewallRule, readOnly bool) *FirewallRulesSet {
	this := FirewallRulesSet{}
	this.Id = id
	this.Name = name
	this.Status = status
	this.Rules = rules
	this.ReadOnly = readOnly
	return &this
}

// NewFirewallRulesSetWithDefaults instantiates a new FirewallRulesSet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirewallRulesSetWithDefaults() *FirewallRulesSet {
	this := FirewallRulesSet{}
	return &this
}

// GetId returns the Id field value
func (o *FirewallRulesSet) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FirewallRulesSet) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FirewallRulesSet) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *FirewallRulesSet) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FirewallRulesSet) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FirewallRulesSet) SetName(v string) {
	o.Name = v
}

// GetStatus returns the Status field value
func (o *FirewallRulesSet) GetStatus() FirewallRulesSetStatusEnum {
	if o == nil {
		var ret FirewallRulesSetStatusEnum
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *FirewallRulesSet) GetStatusOk() (*FirewallRulesSetStatusEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *FirewallRulesSet) SetStatus(v FirewallRulesSetStatusEnum) {
	o.Status = v
}

// GetRules returns the Rules field value
func (o *FirewallRulesSet) GetRules() []FirewallRule {
	if o == nil {
		var ret []FirewallRule
		return ret
	}

	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value
// and a boolean to check if the value has been set.
func (o *FirewallRulesSet) GetRulesOk() ([]FirewallRule, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rules, true
}

// SetRules sets field value
func (o *FirewallRulesSet) SetRules(v []FirewallRule) {
	o.Rules = v
}

// GetReadOnly returns the ReadOnly field value
func (o *FirewallRulesSet) GetReadOnly() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ReadOnly
}

// GetReadOnlyOk returns a tuple with the ReadOnly field value
// and a boolean to check if the value has been set.
func (o *FirewallRulesSet) GetReadOnlyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReadOnly, true
}

// SetReadOnly sets field value
func (o *FirewallRulesSet) SetReadOnly(v bool) {
	o.ReadOnly = v
}

func (o FirewallRulesSet) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FirewallRulesSet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status
	toSerialize["rules"] = o.Rules
	toSerialize["read_only"] = o.ReadOnly
	return toSerialize, nil
}

func (o *FirewallRulesSet) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"status",
		"rules",
		"read_only",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFirewallRulesSet := _FirewallRulesSet{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFirewallRulesSet)

	if err != nil {
		return err
	}

	*o = FirewallRulesSet(varFirewallRulesSet)

	return err
}

type NullableFirewallRulesSet struct {
	value *FirewallRulesSet
	isSet bool
}

func (v NullableFirewallRulesSet) Get() *FirewallRulesSet {
	return v.value
}

func (v *NullableFirewallRulesSet) Set(val *FirewallRulesSet) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallRulesSet) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallRulesSet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallRulesSet(val *FirewallRulesSet) *NullableFirewallRulesSet {
	return &NullableFirewallRulesSet{value: val, isSet: true}
}

func (v NullableFirewallRulesSet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallRulesSet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


