/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VolumeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VolumeRequest{}

// VolumeRequest struct for VolumeRequest
type VolumeRequest struct {
	Project *string `json:"project,omitempty"`
	Alias *string `json:"alias,omitempty"`
	// GB
	Size int32 `json:"size"`
	// ID or slug
	Product string `json:"product"`
}

type _VolumeRequest VolumeRequest

// NewVolumeRequest instantiates a new VolumeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVolumeRequest(size int32, product string) *VolumeRequest {
	this := VolumeRequest{}
	this.Size = size
	this.Product = product
	return &this
}

// NewVolumeRequestWithDefaults instantiates a new VolumeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVolumeRequestWithDefaults() *VolumeRequest {
	this := VolumeRequest{}
	return &this
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *VolumeRequest) GetProject() string {
	if o == nil || IsNil(o.Project) {
		var ret string
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VolumeRequest) GetProjectOk() (*string, bool) {
	if o == nil || IsNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *VolumeRequest) HasProject() bool {
	if o != nil && !IsNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given string and assigns it to the Project field.
func (o *VolumeRequest) SetProject(v string) {
	o.Project = &v
}

// GetAlias returns the Alias field value if set, zero value otherwise.
func (o *VolumeRequest) GetAlias() string {
	if o == nil || IsNil(o.Alias) {
		var ret string
		return ret
	}
	return *o.Alias
}

// GetAliasOk returns a tuple with the Alias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VolumeRequest) GetAliasOk() (*string, bool) {
	if o == nil || IsNil(o.Alias) {
		return nil, false
	}
	return o.Alias, true
}

// HasAlias returns a boolean if a field has been set.
func (o *VolumeRequest) HasAlias() bool {
	if o != nil && !IsNil(o.Alias) {
		return true
	}

	return false
}

// SetAlias gets a reference to the given string and assigns it to the Alias field.
func (o *VolumeRequest) SetAlias(v string) {
	o.Alias = &v
}

// GetSize returns the Size field value
func (o *VolumeRequest) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *VolumeRequest) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *VolumeRequest) SetSize(v int32) {
	o.Size = v
}

// GetProduct returns the Product field value
func (o *VolumeRequest) GetProduct() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Product
}

// GetProductOk returns a tuple with the Product field value
// and a boolean to check if the value has been set.
func (o *VolumeRequest) GetProductOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Product, true
}

// SetProduct sets field value
func (o *VolumeRequest) SetProduct(v string) {
	o.Product = v
}

func (o VolumeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VolumeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	if !IsNil(o.Alias) {
		toSerialize["alias"] = o.Alias
	}
	toSerialize["size"] = o.Size
	toSerialize["product"] = o.Product
	return toSerialize, nil
}

func (o *VolumeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"size",
		"product",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVolumeRequest := _VolumeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varVolumeRequest)

	if err != nil {
		return err
	}

	*o = VolumeRequest(varVolumeRequest)

	return err
}

type NullableVolumeRequest struct {
	value *VolumeRequest
	isSet bool
}

func (v NullableVolumeRequest) Get() *VolumeRequest {
	return v.value
}

func (v *NullableVolumeRequest) Set(val *VolumeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVolumeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVolumeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVolumeRequest(val *VolumeRequest) *NullableVolumeRequest {
	return &NullableVolumeRequest{value: val, isSet: true}
}

func (v NullableVolumeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVolumeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


