/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FeatureUpgradeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeatureUpgradeResponse{}

// FeatureUpgradeResponse struct for FeatureUpgradeResponse
type FeatureUpgradeResponse struct {
	Status string `json:"status"`
	Message string `json:"message"`
}

type _FeatureUpgradeResponse FeatureUpgradeResponse

// NewFeatureUpgradeResponse instantiates a new FeatureUpgradeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeatureUpgradeResponse(status string, message string) *FeatureUpgradeResponse {
	this := FeatureUpgradeResponse{}
	this.Status = status
	this.Message = message
	return &this
}

// NewFeatureUpgradeResponseWithDefaults instantiates a new FeatureUpgradeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeatureUpgradeResponseWithDefaults() *FeatureUpgradeResponse {
	this := FeatureUpgradeResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *FeatureUpgradeResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *FeatureUpgradeResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *FeatureUpgradeResponse) SetStatus(v string) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *FeatureUpgradeResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *FeatureUpgradeResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *FeatureUpgradeResponse) SetMessage(v string) {
	o.Message = v
}

func (o FeatureUpgradeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeatureUpgradeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *FeatureUpgradeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFeatureUpgradeResponse := _FeatureUpgradeResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFeatureUpgradeResponse)

	if err != nil {
		return err
	}

	*o = FeatureUpgradeResponse(varFeatureUpgradeResponse)

	return err
}

type NullableFeatureUpgradeResponse struct {
	value *FeatureUpgradeResponse
	isSet bool
}

func (v NullableFeatureUpgradeResponse) Get() *FeatureUpgradeResponse {
	return v.value
}

func (v *NullableFeatureUpgradeResponse) Set(val *FeatureUpgradeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureUpgradeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureUpgradeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureUpgradeResponse(val *FeatureUpgradeResponse) *NullableFeatureUpgradeResponse {
	return &NullableFeatureUpgradeResponse{value: val, isSet: true}
}

func (v NullableFeatureUpgradeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureUpgradeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


