/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"fmt"
)

// StatusEf2Enum * `new` - New * `answered` - Staff answered * `reply` - Customer replied * `closed` - Closed
type StatusEf2Enum string

// List of StatusEf2Enum
const (
	STATUSEF2ENUM_NEW StatusEf2Enum = "new"
	STATUSEF2ENUM_ANSWERED StatusEf2Enum = "answered"
	STATUSEF2ENUM_REPLY StatusEf2Enum = "reply"
	STATUSEF2ENUM_CLOSED StatusEf2Enum = "closed"
)

// All allowed values of StatusEf2Enum enum
var AllowedStatusEf2EnumEnumValues = []StatusEf2Enum{
	"new",
	"answered",
	"reply",
	"closed",
}

func (v *StatusEf2Enum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := StatusEf2Enum(value)
	for _, existing := range AllowedStatusEf2EnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid StatusEf2Enum", value)
}

// NewStatusEf2EnumFromValue returns a pointer to a valid StatusEf2Enum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewStatusEf2EnumFromValue(v string) (*StatusEf2Enum, error) {
	ev := StatusEf2Enum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for StatusEf2Enum: valid values are %v", v, AllowedStatusEf2EnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v StatusEf2Enum) IsValid() bool {
	for _, existing := range AllowedStatusEf2EnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to StatusEf2Enum value
func (v StatusEf2Enum) Ptr() *StatusEf2Enum {
	return &v
}

type NullableStatusEf2Enum struct {
	value *StatusEf2Enum
	isSet bool
}

func (v NullableStatusEf2Enum) Get() *StatusEf2Enum {
	return v.value
}

func (v *NullableStatusEf2Enum) Set(val *StatusEf2Enum) {
	v.value = val
	v.isSet = true
}

func (v NullableStatusEf2Enum) IsSet() bool {
	return v.isSet
}

func (v *NullableStatusEf2Enum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatusEf2Enum(val *StatusEf2Enum) *NullableStatusEf2Enum {
	return &NullableStatusEf2Enum{value: val, isSet: true}
}

func (v NullableStatusEf2Enum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatusEf2Enum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

