/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
)

// checks if the ChangeCompanyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangeCompanyRequest{}

// ChangeCompanyRequest struct for ChangeCompanyRequest
type ChangeCompanyRequest struct {
	CompanyId NullableInt32 `json:"company_id,omitempty"`
}

// NewChangeCompanyRequest instantiates a new ChangeCompanyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangeCompanyRequest() *ChangeCompanyRequest {
	this := ChangeCompanyRequest{}
	return &this
}

// NewChangeCompanyRequestWithDefaults instantiates a new ChangeCompanyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangeCompanyRequestWithDefaults() *ChangeCompanyRequest {
	this := ChangeCompanyRequest{}
	return &this
}

// GetCompanyId returns the CompanyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChangeCompanyRequest) GetCompanyId() int32 {
	if o == nil || IsNil(o.CompanyId.Get()) {
		var ret int32
		return ret
	}
	return *o.CompanyId.Get()
}

// GetCompanyIdOk returns a tuple with the CompanyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChangeCompanyRequest) GetCompanyIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompanyId.Get(), o.CompanyId.IsSet()
}

// HasCompanyId returns a boolean if a field has been set.
func (o *ChangeCompanyRequest) HasCompanyId() bool {
	if o != nil && o.CompanyId.IsSet() {
		return true
	}

	return false
}

// SetCompanyId gets a reference to the given NullableInt32 and assigns it to the CompanyId field.
func (o *ChangeCompanyRequest) SetCompanyId(v int32) {
	o.CompanyId.Set(&v)
}
// SetCompanyIdNil sets the value for CompanyId to be an explicit nil
func (o *ChangeCompanyRequest) SetCompanyIdNil() {
	o.CompanyId.Set(nil)
}

// UnsetCompanyId ensures that no value is present for CompanyId, not even an explicit nil
func (o *ChangeCompanyRequest) UnsetCompanyId() {
	o.CompanyId.Unset()
}

func (o ChangeCompanyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangeCompanyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CompanyId.IsSet() {
		toSerialize["company_id"] = o.CompanyId.Get()
	}
	return toSerialize, nil
}

type NullableChangeCompanyRequest struct {
	value *ChangeCompanyRequest
	isSet bool
}

func (v NullableChangeCompanyRequest) Get() *ChangeCompanyRequest {
	return v.value
}

func (v *NullableChangeCompanyRequest) Set(val *ChangeCompanyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeCompanyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeCompanyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeCompanyRequest(val *ChangeCompanyRequest) *NullableChangeCompanyRequest {
	return &NullableChangeCompanyRequest{value: val, isSet: true}
}

func (v NullableChangeCompanyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeCompanyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


