/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResourcePool type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourcePool{}

// ResourcePool struct for ResourcePool
type ResourcePool struct {
	Id int32 `json:"id"`
	Package string `json:"package"`
	Size string `json:"size"`
	Nodes []ResourcePoolNode `json:"nodes"`
	NewSize *int32 `json:"new_size,omitempty"`
}

type _ResourcePool ResourcePool

// NewResourcePool instantiates a new ResourcePool object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourcePool(id int32, package_ string, size string, nodes []ResourcePoolNode) *ResourcePool {
	this := ResourcePool{}
	this.Id = id
	this.Package = package_
	this.Size = size
	this.Nodes = nodes
	return &this
}

// NewResourcePoolWithDefaults instantiates a new ResourcePool object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourcePoolWithDefaults() *ResourcePool {
	this := ResourcePool{}
	return &this
}

// GetId returns the Id field value
func (o *ResourcePool) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ResourcePool) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ResourcePool) SetId(v int32) {
	o.Id = v
}

// GetPackage returns the Package field value
func (o *ResourcePool) GetPackage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Package
}

// GetPackageOk returns a tuple with the Package field value
// and a boolean to check if the value has been set.
func (o *ResourcePool) GetPackageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Package, true
}

// SetPackage sets field value
func (o *ResourcePool) SetPackage(v string) {
	o.Package = v
}

// GetSize returns the Size field value
func (o *ResourcePool) GetSize() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *ResourcePool) GetSizeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *ResourcePool) SetSize(v string) {
	o.Size = v
}

// GetNodes returns the Nodes field value
func (o *ResourcePool) GetNodes() []ResourcePoolNode {
	if o == nil {
		var ret []ResourcePoolNode
		return ret
	}

	return o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value
// and a boolean to check if the value has been set.
func (o *ResourcePool) GetNodesOk() ([]ResourcePoolNode, bool) {
	if o == nil {
		return nil, false
	}
	return o.Nodes, true
}

// SetNodes sets field value
func (o *ResourcePool) SetNodes(v []ResourcePoolNode) {
	o.Nodes = v
}

// GetNewSize returns the NewSize field value if set, zero value otherwise.
func (o *ResourcePool) GetNewSize() int32 {
	if o == nil || IsNil(o.NewSize) {
		var ret int32
		return ret
	}
	return *o.NewSize
}

// GetNewSizeOk returns a tuple with the NewSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourcePool) GetNewSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.NewSize) {
		return nil, false
	}
	return o.NewSize, true
}

// HasNewSize returns a boolean if a field has been set.
func (o *ResourcePool) HasNewSize() bool {
	if o != nil && !IsNil(o.NewSize) {
		return true
	}

	return false
}

// SetNewSize gets a reference to the given int32 and assigns it to the NewSize field.
func (o *ResourcePool) SetNewSize(v int32) {
	o.NewSize = &v
}

func (o ResourcePool) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourcePool) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["package"] = o.Package
	toSerialize["size"] = o.Size
	toSerialize["nodes"] = o.Nodes
	if !IsNil(o.NewSize) {
		toSerialize["new_size"] = o.NewSize
	}
	return toSerialize, nil
}

func (o *ResourcePool) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"package",
		"size",
		"nodes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourcePool := _ResourcePool{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResourcePool)

	if err != nil {
		return err
	}

	*o = ResourcePool(varResourcePool)

	return err
}

type NullableResourcePool struct {
	value *ResourcePool
	isSet bool
}

func (v NullableResourcePool) Get() *ResourcePool {
	return v.value
}

func (v *NullableResourcePool) Set(val *ResourcePool) {
	v.value = val
	v.isSet = true
}

func (v NullableResourcePool) IsSet() bool {
	return v.isSet
}

func (v *NullableResourcePool) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourcePool(val *ResourcePool) *NullableResourcePool {
	return &NullableResourcePool{value: val, isSet: true}
}

func (v NullableResourcePool) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourcePool) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


