/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"fmt"
)

// DNSRecordCreateTypeEnum * `A` - A * `AAAA` - AAAA * `TYPE257` - TYPE257 * `CNAME` - CNAME * `MX` - MX * `SRV` - SRV * `TXT` - TXT
type DNSRecordCreateTypeEnum string

// List of DNSRecordCreateTypeEnum
const (
	DNSRECORDCREATETYPEENUM_A DNSRecordCreateTypeEnum = "A"
	DNSRECORDCREATETYPEENUM_AAAA DNSRecordCreateTypeEnum = "AAAA"
	DNSRECORDCREATETYPEENUM_TYPE257 DNSRecordCreateTypeEnum = "TYPE257"
	DNSRECORDCREATETYPEENUM_CNAME DNSRecordCreateTypeEnum = "CNAME"
	DNSRECORDCREATETYPEENUM_MX DNSRecordCreateTypeEnum = "MX"
	DNSRECORDCREATETYPEENUM_SRV DNSRecordCreateTypeEnum = "SRV"
	DNSRECORDCREATETYPEENUM_TXT DNSRecordCreateTypeEnum = "TXT"
)

// All allowed values of DNSRecordCreateTypeEnum enum
var AllowedDNSRecordCreateTypeEnumEnumValues = []DNSRecordCreateTypeEnum{
	"A",
	"AAAA",
	"TYPE257",
	"CNAME",
	"MX",
	"SRV",
	"TXT",
}

func (v *DNSRecordCreateTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DNSRecordCreateTypeEnum(value)
	for _, existing := range AllowedDNSRecordCreateTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DNSRecordCreateTypeEnum", value)
}

// NewDNSRecordCreateTypeEnumFromValue returns a pointer to a valid DNSRecordCreateTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDNSRecordCreateTypeEnumFromValue(v string) (*DNSRecordCreateTypeEnum, error) {
	ev := DNSRecordCreateTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DNSRecordCreateTypeEnum: valid values are %v", v, AllowedDNSRecordCreateTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DNSRecordCreateTypeEnum) IsValid() bool {
	for _, existing := range AllowedDNSRecordCreateTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DNSRecordCreateTypeEnum value
func (v DNSRecordCreateTypeEnum) Ptr() *DNSRecordCreateTypeEnum {
	return &v
}

type NullableDNSRecordCreateTypeEnum struct {
	value *DNSRecordCreateTypeEnum
	isSet bool
}

func (v NullableDNSRecordCreateTypeEnum) Get() *DNSRecordCreateTypeEnum {
	return v.value
}

func (v *NullableDNSRecordCreateTypeEnum) Set(val *DNSRecordCreateTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableDNSRecordCreateTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableDNSRecordCreateTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDNSRecordCreateTypeEnum(val *DNSRecordCreateTypeEnum) *NullableDNSRecordCreateTypeEnum {
	return &NullableDNSRecordCreateTypeEnum{value: val, isSet: true}
}

func (v NullableDNSRecordCreateTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDNSRecordCreateTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

