/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PublicIPv4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicIPv4{}

// PublicIPv4 struct for PublicIPv4
type PublicIPv4 struct {
	Id int32 `json:"id"`
	Slug string `json:"slug"`
	Address string `json:"address"`
	Gateway string `json:"gateway"`
	Prefix int32 `json:"prefix"`
	Attached bool `json:"attached"`
	Server string `json:"server"`
}

type _PublicIPv4 PublicIPv4

// NewPublicIPv4 instantiates a new PublicIPv4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicIPv4(id int32, slug string, address string, gateway string, prefix int32, attached bool, server string) *PublicIPv4 {
	this := PublicIPv4{}
	this.Id = id
	this.Slug = slug
	this.Address = address
	this.Gateway = gateway
	this.Prefix = prefix
	this.Attached = attached
	this.Server = server
	return &this
}

// NewPublicIPv4WithDefaults instantiates a new PublicIPv4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicIPv4WithDefaults() *PublicIPv4 {
	this := PublicIPv4{}
	return &this
}

// GetId returns the Id field value
func (o *PublicIPv4) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PublicIPv4) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PublicIPv4) SetId(v int32) {
	o.Id = v
}

// GetSlug returns the Slug field value
func (o *PublicIPv4) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *PublicIPv4) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *PublicIPv4) SetSlug(v string) {
	o.Slug = v
}

// GetAddress returns the Address field value
func (o *PublicIPv4) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *PublicIPv4) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *PublicIPv4) SetAddress(v string) {
	o.Address = v
}

// GetGateway returns the Gateway field value
func (o *PublicIPv4) GetGateway() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Gateway
}

// GetGatewayOk returns a tuple with the Gateway field value
// and a boolean to check if the value has been set.
func (o *PublicIPv4) GetGatewayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gateway, true
}

// SetGateway sets field value
func (o *PublicIPv4) SetGateway(v string) {
	o.Gateway = v
}

// GetPrefix returns the Prefix field value
func (o *PublicIPv4) GetPrefix() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value
// and a boolean to check if the value has been set.
func (o *PublicIPv4) GetPrefixOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prefix, true
}

// SetPrefix sets field value
func (o *PublicIPv4) SetPrefix(v int32) {
	o.Prefix = v
}

// GetAttached returns the Attached field value
func (o *PublicIPv4) GetAttached() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Attached
}

// GetAttachedOk returns a tuple with the Attached field value
// and a boolean to check if the value has been set.
func (o *PublicIPv4) GetAttachedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attached, true
}

// SetAttached sets field value
func (o *PublicIPv4) SetAttached(v bool) {
	o.Attached = v
}

// GetServer returns the Server field value
func (o *PublicIPv4) GetServer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Server
}

// GetServerOk returns a tuple with the Server field value
// and a boolean to check if the value has been set.
func (o *PublicIPv4) GetServerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Server, true
}

// SetServer sets field value
func (o *PublicIPv4) SetServer(v string) {
	o.Server = v
}

func (o PublicIPv4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicIPv4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["slug"] = o.Slug
	toSerialize["address"] = o.Address
	toSerialize["gateway"] = o.Gateway
	toSerialize["prefix"] = o.Prefix
	toSerialize["attached"] = o.Attached
	toSerialize["server"] = o.Server
	return toSerialize, nil
}

func (o *PublicIPv4) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"slug",
		"address",
		"gateway",
		"prefix",
		"attached",
		"server",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublicIPv4 := _PublicIPv4{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPublicIPv4)

	if err != nil {
		return err
	}

	*o = PublicIPv4(varPublicIPv4)

	return err
}

type NullablePublicIPv4 struct {
	value *PublicIPv4
	isSet bool
}

func (v NullablePublicIPv4) Get() *PublicIPv4 {
	return v.value
}

func (v *NullablePublicIPv4) Set(val *PublicIPv4) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicIPv4) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicIPv4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicIPv4(val *PublicIPv4) *NullablePublicIPv4 {
	return &NullablePublicIPv4{value: val, isSet: true}
}

func (v NullablePublicIPv4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicIPv4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


