/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"fmt"
)

// PowerActionActionEnum * `start` - start * `stop` - stop * `restart` - restart * `shutdown` - shutdown
type PowerActionActionEnum string

// List of PowerActionActionEnum
const (
	POWERACTIONACTIONENUM_START PowerActionActionEnum = "start"
	POWERACTIONACTIONENUM_STOP PowerActionActionEnum = "stop"
	POWERACTIONACTIONENUM_RESTART PowerActionActionEnum = "restart"
	POWERACTIONACTIONENUM_SHUTDOWN PowerActionActionEnum = "shutdown"
)

// All allowed values of PowerActionActionEnum enum
var AllowedPowerActionActionEnumEnumValues = []PowerActionActionEnum{
	"start",
	"stop",
	"restart",
	"shutdown",
}

func (v *PowerActionActionEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PowerActionActionEnum(value)
	for _, existing := range AllowedPowerActionActionEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PowerActionActionEnum", value)
}

// NewPowerActionActionEnumFromValue returns a pointer to a valid PowerActionActionEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPowerActionActionEnumFromValue(v string) (*PowerActionActionEnum, error) {
	ev := PowerActionActionEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PowerActionActionEnum: valid values are %v", v, AllowedPowerActionActionEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PowerActionActionEnum) IsValid() bool {
	for _, existing := range AllowedPowerActionActionEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PowerActionActionEnum value
func (v PowerActionActionEnum) Ptr() *PowerActionActionEnum {
	return &v
}

type NullablePowerActionActionEnum struct {
	value *PowerActionActionEnum
	isSet bool
}

func (v NullablePowerActionActionEnum) Get() *PowerActionActionEnum {
	return v.value
}

func (v *NullablePowerActionActionEnum) Set(val *PowerActionActionEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePowerActionActionEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePowerActionActionEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePowerActionActionEnum(val *PowerActionActionEnum) *NullablePowerActionActionEnum {
	return &NullablePowerActionActionEnum{value: val, isSet: true}
}

func (v NullablePowerActionActionEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePowerActionActionEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

