/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConnectVMRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectVMRequest{}

// ConnectVMRequest struct for ConnectVMRequest
type ConnectVMRequest struct {
	// VM resource PK or hostname
	Server int32 `json:"server"`
}

type _ConnectVMRequest ConnectVMRequest

// NewConnectVMRequest instantiates a new ConnectVMRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectVMRequest(server int32) *ConnectVMRequest {
	this := ConnectVMRequest{}
	this.Server = server
	return &this
}

// NewConnectVMRequestWithDefaults instantiates a new ConnectVMRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectVMRequestWithDefaults() *ConnectVMRequest {
	this := ConnectVMRequest{}
	return &this
}

// GetServer returns the Server field value
func (o *ConnectVMRequest) GetServer() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Server
}

// GetServerOk returns a tuple with the Server field value
// and a boolean to check if the value has been set.
func (o *ConnectVMRequest) GetServerOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Server, true
}

// SetServer sets field value
func (o *ConnectVMRequest) SetServer(v int32) {
	o.Server = v
}

func (o ConnectVMRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectVMRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["server"] = o.Server
	return toSerialize, nil
}

func (o *ConnectVMRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"server",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectVMRequest := _ConnectVMRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConnectVMRequest)

	if err != nil {
		return err
	}

	*o = ConnectVMRequest(varConnectVMRequest)

	return err
}

type NullableConnectVMRequest struct {
	value *ConnectVMRequest
	isSet bool
}

func (v NullableConnectVMRequest) Get() *ConnectVMRequest {
	return v.value
}

func (v *NullableConnectVMRequest) Set(val *ConnectVMRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectVMRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectVMRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectVMRequest(val *ConnectVMRequest) *NullableConnectVMRequest {
	return &NullableConnectVMRequest{value: val, isSet: true}
}

func (v NullableConnectVMRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectVMRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


