/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NodeMetricsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodeMetricsResponse{}

// NodeMetricsResponse struct for NodeMetricsResponse
type NodeMetricsResponse struct {
	Cpu float64 `json:"cpu"`
	Mem int32 `json:"mem"`
	Maxmem int32 `json:"maxmem"`
	Status string `json:"status"`
	Uptime int32 `json:"uptime"`
	Netin int32 `json:"netin"`
	Netout int32 `json:"netout"`
}

type _NodeMetricsResponse NodeMetricsResponse

// NewNodeMetricsResponse instantiates a new NodeMetricsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodeMetricsResponse(cpu float64, mem int32, maxmem int32, status string, uptime int32, netin int32, netout int32) *NodeMetricsResponse {
	this := NodeMetricsResponse{}
	this.Cpu = cpu
	this.Mem = mem
	this.Maxmem = maxmem
	this.Status = status
	this.Uptime = uptime
	this.Netin = netin
	this.Netout = netout
	return &this
}

// NewNodeMetricsResponseWithDefaults instantiates a new NodeMetricsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodeMetricsResponseWithDefaults() *NodeMetricsResponse {
	this := NodeMetricsResponse{}
	return &this
}

// GetCpu returns the Cpu field value
func (o *NodeMetricsResponse) GetCpu() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value
// and a boolean to check if the value has been set.
func (o *NodeMetricsResponse) GetCpuOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cpu, true
}

// SetCpu sets field value
func (o *NodeMetricsResponse) SetCpu(v float64) {
	o.Cpu = v
}

// GetMem returns the Mem field value
func (o *NodeMetricsResponse) GetMem() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Mem
}

// GetMemOk returns a tuple with the Mem field value
// and a boolean to check if the value has been set.
func (o *NodeMetricsResponse) GetMemOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mem, true
}

// SetMem sets field value
func (o *NodeMetricsResponse) SetMem(v int32) {
	o.Mem = v
}

// GetMaxmem returns the Maxmem field value
func (o *NodeMetricsResponse) GetMaxmem() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Maxmem
}

// GetMaxmemOk returns a tuple with the Maxmem field value
// and a boolean to check if the value has been set.
func (o *NodeMetricsResponse) GetMaxmemOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Maxmem, true
}

// SetMaxmem sets field value
func (o *NodeMetricsResponse) SetMaxmem(v int32) {
	o.Maxmem = v
}

// GetStatus returns the Status field value
func (o *NodeMetricsResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *NodeMetricsResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *NodeMetricsResponse) SetStatus(v string) {
	o.Status = v
}

// GetUptime returns the Uptime field value
func (o *NodeMetricsResponse) GetUptime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Uptime
}

// GetUptimeOk returns a tuple with the Uptime field value
// and a boolean to check if the value has been set.
func (o *NodeMetricsResponse) GetUptimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uptime, true
}

// SetUptime sets field value
func (o *NodeMetricsResponse) SetUptime(v int32) {
	o.Uptime = v
}

// GetNetin returns the Netin field value
func (o *NodeMetricsResponse) GetNetin() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Netin
}

// GetNetinOk returns a tuple with the Netin field value
// and a boolean to check if the value has been set.
func (o *NodeMetricsResponse) GetNetinOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Netin, true
}

// SetNetin sets field value
func (o *NodeMetricsResponse) SetNetin(v int32) {
	o.Netin = v
}

// GetNetout returns the Netout field value
func (o *NodeMetricsResponse) GetNetout() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Netout
}

// GetNetoutOk returns a tuple with the Netout field value
// and a boolean to check if the value has been set.
func (o *NodeMetricsResponse) GetNetoutOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Netout, true
}

// SetNetout sets field value
func (o *NodeMetricsResponse) SetNetout(v int32) {
	o.Netout = v
}

func (o NodeMetricsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodeMetricsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cpu"] = o.Cpu
	toSerialize["mem"] = o.Mem
	toSerialize["maxmem"] = o.Maxmem
	toSerialize["status"] = o.Status
	toSerialize["uptime"] = o.Uptime
	toSerialize["netin"] = o.Netin
	toSerialize["netout"] = o.Netout
	return toSerialize, nil
}

func (o *NodeMetricsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cpu",
		"mem",
		"maxmem",
		"status",
		"uptime",
		"netin",
		"netout",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodeMetricsResponse := _NodeMetricsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varNodeMetricsResponse)

	if err != nil {
		return err
	}

	*o = NodeMetricsResponse(varNodeMetricsResponse)

	return err
}

type NullableNodeMetricsResponse struct {
	value *NodeMetricsResponse
	isSet bool
}

func (v NullableNodeMetricsResponse) Get() *NodeMetricsResponse {
	return v.value
}

func (v *NullableNodeMetricsResponse) Set(val *NodeMetricsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNodeMetricsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNodeMetricsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodeMetricsResponse(val *NodeMetricsResponse) *NullableNodeMetricsResponse {
	return &NullableNodeMetricsResponse{value: val, isSet: true}
}

func (v NullableNodeMetricsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodeMetricsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


