/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DNSRecordMutateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DNSRecordMutateResponse{}

// DNSRecordMutateResponse struct for DNSRecordMutateResponse
type DNSRecordMutateResponse struct {
	Message string `json:"message"`
	Record *DNSRecord `json:"record,omitempty"`
}

type _DNSRecordMutateResponse DNSRecordMutateResponse

// NewDNSRecordMutateResponse instantiates a new DNSRecordMutateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDNSRecordMutateResponse(message string) *DNSRecordMutateResponse {
	this := DNSRecordMutateResponse{}
	this.Message = message
	return &this
}

// NewDNSRecordMutateResponseWithDefaults instantiates a new DNSRecordMutateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDNSRecordMutateResponseWithDefaults() *DNSRecordMutateResponse {
	this := DNSRecordMutateResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *DNSRecordMutateResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *DNSRecordMutateResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *DNSRecordMutateResponse) SetMessage(v string) {
	o.Message = v
}

// GetRecord returns the Record field value if set, zero value otherwise.
func (o *DNSRecordMutateResponse) GetRecord() DNSRecord {
	if o == nil || IsNil(o.Record) {
		var ret DNSRecord
		return ret
	}
	return *o.Record
}

// GetRecordOk returns a tuple with the Record field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DNSRecordMutateResponse) GetRecordOk() (*DNSRecord, bool) {
	if o == nil || IsNil(o.Record) {
		return nil, false
	}
	return o.Record, true
}

// HasRecord returns a boolean if a field has been set.
func (o *DNSRecordMutateResponse) HasRecord() bool {
	if o != nil && !IsNil(o.Record) {
		return true
	}

	return false
}

// SetRecord gets a reference to the given DNSRecord and assigns it to the Record field.
func (o *DNSRecordMutateResponse) SetRecord(v DNSRecord) {
	o.Record = &v
}

func (o DNSRecordMutateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DNSRecordMutateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	if !IsNil(o.Record) {
		toSerialize["record"] = o.Record
	}
	return toSerialize, nil
}

func (o *DNSRecordMutateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDNSRecordMutateResponse := _DNSRecordMutateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varDNSRecordMutateResponse)

	if err != nil {
		return err
	}

	*o = DNSRecordMutateResponse(varDNSRecordMutateResponse)

	return err
}

type NullableDNSRecordMutateResponse struct {
	value *DNSRecordMutateResponse
	isSet bool
}

func (v NullableDNSRecordMutateResponse) Get() *DNSRecordMutateResponse {
	return v.value
}

func (v *NullableDNSRecordMutateResponse) Set(val *DNSRecordMutateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDNSRecordMutateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDNSRecordMutateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDNSRecordMutateResponse(val *DNSRecordMutateResponse) *NullableDNSRecordMutateResponse {
	return &NullableDNSRecordMutateResponse{value: val, isSet: true}
}

func (v NullableDNSRecordMutateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDNSRecordMutateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


