/*
Pidgin Host API

The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.

API version: 1.0.0 (v1)
Contact: support@pidginhost.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pidginhostsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the K8sPortForwardRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &K8sPortForwardRequest{}

// K8sPortForwardRequest struct for K8sPortForwardRequest
type K8sPortForwardRequest struct {
	InternalIp string `json:"internal_ip"`
	Port int32 `json:"port"`
	Protocol ProtocolEnum `json:"protocol"`
}

type _K8sPortForwardRequest K8sPortForwardRequest

// NewK8sPortForwardRequest instantiates a new K8sPortForwardRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewK8sPortForwardRequest(internalIp string, port int32, protocol ProtocolEnum) *K8sPortForwardRequest {
	this := K8sPortForwardRequest{}
	this.InternalIp = internalIp
	this.Port = port
	this.Protocol = protocol
	return &this
}

// NewK8sPortForwardRequestWithDefaults instantiates a new K8sPortForwardRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewK8sPortForwardRequestWithDefaults() *K8sPortForwardRequest {
	this := K8sPortForwardRequest{}
	return &this
}

// GetInternalIp returns the InternalIp field value
func (o *K8sPortForwardRequest) GetInternalIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InternalIp
}

// GetInternalIpOk returns a tuple with the InternalIp field value
// and a boolean to check if the value has been set.
func (o *K8sPortForwardRequest) GetInternalIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InternalIp, true
}

// SetInternalIp sets field value
func (o *K8sPortForwardRequest) SetInternalIp(v string) {
	o.InternalIp = v
}

// GetPort returns the Port field value
func (o *K8sPortForwardRequest) GetPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *K8sPortForwardRequest) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *K8sPortForwardRequest) SetPort(v int32) {
	o.Port = v
}

// GetProtocol returns the Protocol field value
func (o *K8sPortForwardRequest) GetProtocol() ProtocolEnum {
	if o == nil {
		var ret ProtocolEnum
		return ret
	}

	return o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value
// and a boolean to check if the value has been set.
func (o *K8sPortForwardRequest) GetProtocolOk() (*ProtocolEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Protocol, true
}

// SetProtocol sets field value
func (o *K8sPortForwardRequest) SetProtocol(v ProtocolEnum) {
	o.Protocol = v
}

func (o K8sPortForwardRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o K8sPortForwardRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["internal_ip"] = o.InternalIp
	toSerialize["port"] = o.Port
	toSerialize["protocol"] = o.Protocol
	return toSerialize, nil
}

func (o *K8sPortForwardRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"internal_ip",
		"port",
		"protocol",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varK8sPortForwardRequest := _K8sPortForwardRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varK8sPortForwardRequest)

	if err != nil {
		return err
	}

	*o = K8sPortForwardRequest(varK8sPortForwardRequest)

	return err
}

type NullableK8sPortForwardRequest struct {
	value *K8sPortForwardRequest
	isSet bool
}

func (v NullableK8sPortForwardRequest) Get() *K8sPortForwardRequest {
	return v.value
}

func (v *NullableK8sPortForwardRequest) Set(val *K8sPortForwardRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableK8sPortForwardRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableK8sPortForwardRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableK8sPortForwardRequest(val *K8sPortForwardRequest) *NullableK8sPortForwardRequest {
	return &NullableK8sPortForwardRequest{value: val, isSet: true}
}

func (v NullableK8sPortForwardRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableK8sPortForwardRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


